singulars:
  mainSkill:
    text: While doing <skill skill="{skill}"/>.
  mainSkillType:
    text: While doing <skillType type="{type}"/> skills.
  skillLevel:
    text: At least <skill skill="{skill}" level="{level}" needed/>.
  traveling:
    text: While traveling.
  itemAnywhereWithYou:
    text: Have item <item id="{item}"/> with you.
  itemEquipped:
    text: Have item <item id="{item}"/> equipped.
  itemInInventory:
    text: Have item <item id="{item}"/> in your inventory.
  itemAnywhere:
    text: Have item <item id="{item}"/>.
  itemQualityEquipped:
    text: Have at least <numberProgress current="{current}" max="{max}" /> <itemQuality quality="{quality}" type="{type}"/> items equipped.
    withoutType: Have at least <numberProgress current="{current}" max="{max}" /> <itemQuality quality="{quality}" type="crafted"/> or <itemQuality quality="{quality}" type="loot"/> items equipped.
  keywordEquipped:
    text: Have <object id="{obj}" /> equipped.
  keywordWithLevelEquipped:
    text: Have <object id="{obj}" /> equipped that requires at least <skill skill="{skill}"/> level <numberProgress current="{current}" max="{max}" />.
  distinctItemsEquippedKeyword:
    text: Requires <numberProgress current="{current}" max="{max}" /> unique <object id="{obj}" /> equipped.
  totalSteps:
    text: Have <numberProgress current="{current}" max="{max}" /> steps walked in total.
  characterLevel:
    text: Have character level <numberProgress current="{current}" max="{max}" />.
  unlocked:
    text: Have unlocked <object id="{obj}" alwaysShow="true" />.
  achievementPoints:
    text: Have <icon i="achievement point"/> <numberProgress current="{current}" max="{max}" /> achievement points.
  achievementPointsPercent:
    text: Have <icon i="achievement point"/> <numberProgress current="{current}" max="{max}" /> achievement points ({percentage}% of total).
  haveCoins:
    text: Have <icon i="money small"/> <numberProgress current="{current}" max="{max}" /> coins.
  minimumSkillLevel:
    text: Have every skill at least level <numberProgress current="{current}" max="{max}" />.
  levelUpSkills:
    text: Have a <numberProgress current="{current}" max="{max}" /> total skill level.
  overencumbered:
    text: Have your inventory over the limit (overencumbered).
  haveItemStack:
    text: Have an item stack of <object id="{obj}" alwaysShow="true" /> with size of <numberProgress current="{current}" max="{max}" />.
  exploreRealm:
    text: Explore <object id="{obj}" alwaysShow="true" /> completely. <numberProgress current="{current}" max="{max}" />.
  haveBankStacks:
    text: Have <numberProgress current="{current}" max="{max}" /> stacks of items in your bank.
  activityType:
    singleKeyword: While doing <object id="{obj}" /> activity.
  service:
    text: Needs <serviceTier tier="{tier}" /> <object id="{obj}" /> service or better.
  realm:
    text: While in the <realm realm="{realm}" /> area.
  locationHasKeywords:
    text: While in <object id="{obj}" /> location.
  uniques:
    beginnerCrossCountry: Complete the <object id="activity-cross-country_skiing_(beginner)-fc421940-d63a-402f-aa50-26cc2efea4d3" alwaysShow="true" /> activity <numberProgress current="{current}" max="{max}" /> times.
    intermediateCrossCountry:  Complete the <object id="activity-cross-country_skiing_(intermediate)-42788047-6cc3-4711-88be-999e9504fc2a" alwaysShow="true" /> activity <numberProgress current="{current}" max="{max}" /> times.
    firewoodMaking:  Complete the <object id="activity-firewood_making-407263a4-4ee1-4383-a624-2a7ed70c4b10" alwaysShow="true" /> activity <numberProgress current="{current}" max="{max}" /> times.
    woodCarving: Complete the <object id="activity-wood_carving-af675674-c972-4e2e-80fe-1501b972e353" alwaysShow="true" /> activity <numberProgress current="{current}" max="{max}" /> times.
    searchTeam: Complete the Black Eye Peak <object id="activity-black_eye_peak_search_team-d1ad835f-0898-4fc7-8f0a-4b0626d95306" alwaysShow="true" /> activity in <object id="location-horn_of_respite-1661d247-11f1-49eb-b927-6e59c8fd7774" alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> times.
    intermediateShipRepair: Complete the <object id="activity-ship_repair_(intermediate)-44f2f2e7-bef1-437f-ac35-bf64b97cc249" alwaysShow="true" /> activity <numberProgress current="{current}" max="{max}" /> times.
    wreckDiving: Complete the <object id="activity-wreck_diving-12e980cd-058a-42c4-8358-ba7afe1c319c" alwaysShow="true" /> activity <numberProgress current="{current}" max="{max}" /> times.
  gear:
    swimmingExpert: Have completed the <object id="activity-swimming_(expert)-95a78afb-79f0-431c-b7aa-062659d9ec87" alwaysShow="true" /> activity <numberProgress current="{current}" max="{max}" /> times.
    tinkering: Have completed the <object id="activity-tinkering-cb2a8773-06d0-4661-9708-2bef5768119e" /> activity <numberProgress current="{current}" max="{max}" /> times in <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a" alwaysShow="true" />
    underwaterBasketweaving: Have completed the <object id="activity-underwater_basket_weaving-7ba725a2-d147-437c-98bf-5a9f58d68b65" alwaysShow="true" /> activity <numberProgress current="{current}" max="{max}" /> times in <object id="location-fertile_shallows-6561e4b5-fce3-4307-a641-86ca5aee36d6" alwaysShow="true" />
    iceSculpting: Have completed the <object id="activity-ice_sculpting-2b0be0f5-69d5-4205-922d-c5a02c056cab" alwaysShow="true" /> activity  <numberProgress current="{current}" max="{max}" /> times in <object id="location-frusenholm-5ddb0735-4582-4858-80a0-7489f1b043a2" alwaysShow="true" />
    beginnerSkydisc: Have completed the <object id="activity-frisbee_golfing_(beginner)-0fb41f4d-f46b-4a6d-acdf-f2525654c714" alwaysShow="true" /> activity in <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a" alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> times.
    sledding: While doing <object id="activity-sledding-290bfd6c-3bb1-47c6-bf60-880c1d4a5148" /> activity.
  maps:
    jarvoniaMap: Own a <object id="item-map_of_jarvonia-86ba96b3-a845-4f5c-a054-04ec5146fb25" />.
    syrenthiaMap: Own a <object id="65979ee2-f98a-41c3-9f12-8858000017a3" />.
    trellinMap: Own a <object id="item-map_of_gdte-b28951b2-2cac-4e53-b6f1-bc2030590433" />.
    erdwiseMap: Own a <object id="fa277527-585b-4a1d-bc73-a25fe1195017" />.
    halflingMap: Own a <object id="f1a9e370-fd69-4a49-92c0-c83475a896ab" />.
  factionReputations:
    jarvoniaReputation: Have <numberProgress current="{current}" max="{max}" /> <realm realm="faction-jarvonia-1b061315-a63d-4dc1-a8ba-10902a83c5db" /> faction reputation.
    syrenthiaReputation: Have <numberProgress current="{current}" max="{max}" /> <realm realm="faction-syrenthia-6e9359fa-597b-4448-9df5-cc3fff9a5108" /> faction reputation.
    trellinReputation: Have <numberProgress current="{current}" max="{max}" /> <realm realm="faction-trellin-239a0ad8-3812-4f2a-9c11-1c312490249b" /> faction reputation.
    erdwiseReputation: Have <numberProgress current="{current}" max="{max}" /> <realm realm="faction-erdwise-697ae8a6-491e-46fd-8a05-4b744f9630eb" /> faction reputation.
    halflingRebelsReputation: Have <numberProgress current="{current}" max="{max}" /> <realm realm="faction-halfling_rebels-394eaff8-2749-4473-949c-80da531a415e" /> faction reputation.