singulars:
  traveling:
    text: Při cestování
  achievementPoints:
    text: Máte <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> bodů úspěchu.
  skillLevel:
    text: Alespoň <skill skill="{skill}" level="{level}" needed/>
  achievementPointsPercent:
    text: Máte <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> bodů úspěchu ({percentage}% z celkového počtu).
  service:
    text: Vyžaduje <serviceTier tier="{tier}" /> <object id="{obj}" /> nebo lepší.
  mainSkill:
    text: Během provádění <skill skill="{skill}"/>
  activityType:
    singleKeyword: Během aktivity <object id="{obj}" />.
  realm:
    text: Dokud se nacházíte v <realm realm="{realm}" />.
