singulars:
  traveling:
    text: Při cestování
  achievementPoints:
    text: Máte <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> bodů úspěchu.
  skillLevel:
    text: Alespoň <skill skill="{skill}" level="{level}" needed/>
  achievementPointsPercent:
    text: Máte <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> bodů úspěchu ({percentage}% z celkového počtu).
  service:
    text: Vyžaduje <serviceTier tier="{tier}" /> <object id="{obj}" /> nebo lepší.
  mainSkill:
    text: Během provádění <skill skill="{skill}"/>
  activityType:
    singleKeyword: Během aktivity <object id="{obj}" />.
  realm:
    text: Dokud se nacházíte v <realm realm="{realm}" />.
  itemInInventory:
    text: Mějte položku <item id="{item}"/> v batohu.
  overencumbered:
    text: Překročili jste limit zásob v batohu (jste přetíženi).
  uniques:
    beginnerCrossCountry: Dokončete <object 
      id="activity-cross-country_skiing_(beginner)-fc421940-d63a-402f-aa50-26cc2efea4d3"
      alwaysShow="true" /> aktivitu <numberProgress current="{current}" max="{max}"
      /> krát.
    firewoodMaking: Dokončete <object id="activity-firewood_making-407263a4-4ee1-4383-a624-2a7ed70c4b10"
      alwaysShow="true" /> aktivitu <numberProgress current="{current}" max="{max}"
      /> krát.
    intermediateCrossCountry: Dokončete <object 
      id="activity-cross-country_skiing_(intermediate)-42788047-6cc3-4711-88be-999e9504fc2a"
      alwaysShow="true" /> aktivitu <numberProgress current="{current}" max="{max}"
      /> krát.
    woodCarving: Dokončete <object id="activity-wood_carving-af675674-c972-4e2e-80fe-1501b972e353"
      alwaysShow="true" /> aktivitu <numberProgress current="{current}" max="{max}"
      /> krát.
    intermediateShipRepair: Dokončete aktivitu <object id="activity-ship_repair_(intermediate)-44f2f2e7-bef1-437f-ac35-bf64b97cc249"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> krát.
  itemAnywhereWithYou:
    text: Mějte s sebou položku <item id="{item}"/>.
  itemEquipped:
    text: Musíte nosit <item id="{item}"/>.
  itemAnywhere:
    text: Mějte položku <item id="{item}"/>.
  characterLevel:
    text: Dosáhněte úrovně postavy <numberProgress current="{current}" max="{max}"
      />.
  unlocked:
    text: Odemkli jste <object id="{obj}" alwaysShow="true" />.
  haveCoins:
    text: Mějte <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> mincí.
  minimumSkillLevel:
    text: Mějte všechny dovednosti alespoň na úrovni <numberProgress current="{current}"
      max="{max}" />.
  levelUpSkills:
    text: Zvyšte úroveň svých dovedností <numberProgress current="{current}" max="{max}"
      /> krát.
  haveBankStacks:
    text: Mějte ve své bance <numberProgress current="{current}" max="{max}" /> hromádek
      položek.
  distinctItemsEquippedKeyword:
    text: Vyžaduje nosit <numberProgress current="{current}" max="{max}" /> unique
      <object id="{obj}" />.
  totalSteps:
    text: Mít celkem <numberProgress current="{current}" max="{max}" /> kroků.
  gear:
    beginnerSkydisc: Dokončete aktivitu <object id="activity-frisbee_golfing_(beginner)-0fb41f4d-f46b-4a6d-acdf-f2525654c714"
      alwaysShow="true" /> v <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> krát.
    swimmingExpert: Dokončete aktivitu <object id="activity-swimming_(expert)-95a78afb-79f0-431c-b7aa-062659d9ec87"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> krát.
