singulars:
  traveling:
    text: Při cestování
  achievementPoints:
    text: Máte <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> bodů úspěchu.
  skillLevel:
    text: Alespoň <skill skill="{skill}" level="{level}" needed/>
  achievementPointsPercent:
    text: Máte <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> bodů úspěchu ({percentage}% z celkového počtu).
  service:
    text: Vyžaduje <serviceTier tier="{tier}" /> <object id="{obj}" /> nebo lepší.
  mainSkill:
    text: Během provádění <skill skill="{skill}"/>
  activityType:
    singleKeyword: Během aktivity <object id="{obj}" />.
  realm:
    text: Dokud se nacházíte v <realm realm="{realm}" />.
  itemInInventory:
    text: Mějte položku <item id="{item}"/> v batohu.
  overencumbered:
    text: Překročili jste limit zásob v batohu (jste přetíženi).
  uniques:
    beginnerCrossCountry: Dokončete aktivitu <object 
      id="activity-cross-country_skiing_(beginner)-fc421940-d63a-402f-aa50-26cc2efea4d3"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> krát.
    firewoodMaking: Dokončete aktivitu <object id="activity-firewood_making-407263a4-4ee1-4383-a624-2a7ed70c4b10"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> krát.
    intermediateCrossCountry: Dokončete aktivitu <object 
      id="activity-cross-country_skiing_(intermediate)-42788047-6cc3-4711-88be-999e9504fc2a"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> krát.
    woodCarving: Dokončete aktivitu <object id="activity-wood_carving-af675674-c972-4e2e-80fe-1501b972e353"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> krát.
    intermediateShipRepair: Dokončete aktivitu <object id="activity-ship_repair_(intermediate)-44f2f2e7-bef1-437f-ac35-bf64b97cc249"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> krát.
    searchTeam: Dokončete Black Eye Peak aktivitu <object id="activity-black_eye_peak_search_team-d1ad835f-0898-4fc7-8f0a-4b0626d95306"
      alwaysShow="true" /> v <object id="location-horn_of_respite-1661d247-11f1-49eb-b927-6e59c8fd7774"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> krát.
  itemAnywhereWithYou:
    text: Mějte s sebou položku <item id="{item}"/>.
  itemEquipped:
    text: Musíte nosit <item id="{item}"/>.
  itemAnywhere:
    text: Mějte položku <item id="{item}"/>.
  characterLevel:
    text: Dosáhněte úrovně postavy <numberProgress current="{current}" max="{max}"
      />.
  unlocked:
    text: Odemkli jste <object id="{obj}" alwaysShow="true" />.
  haveCoins:
    text: Mějte <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> mincí.
  minimumSkillLevel:
    text: Mějte všechny dovednosti alespoň na úrovni <numberProgress current="{current}"
      max="{max}" />.
  levelUpSkills:
    text: Zvyšte úroveň svých dovedností <numberProgress current="{current}" max="{max}"
      /> krát.
  haveBankStacks:
    text: Mějte ve své bance <numberProgress current="{current}" max="{max}" /> hromádek
      položek.
  distinctItemsEquippedKeyword:
    text: Vyžaduje nosit <numberProgress current="{current}" max="{max}" /> unikátní
      <object id="{obj}" />.
  totalSteps:
    text: Mít celkem <numberProgress current="{current}" max="{max}" /> kroků.
  gear:
    beginnerSkydisc: Dokončete aktivitu <object id="activity-frisbee_golfing_(beginner)-0fb41f4d-f46b-4a6d-acdf-f2525654c714"
      alwaysShow="true" /> v <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> krát.
    swimmingExpert: Dokončete aktivitu <object id="activity-swimming_(expert)-95a78afb-79f0-431c-b7aa-062659d9ec87"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> krát.
    tinkering: Ujděte <numberProgress current="{current}" max="{max}" /> kroků během
      aktivity <object id="activity-tinkering-cb2a8773-06d0-4661-9708-2bef5768119e"
      /> v <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a" alwaysShow="true"
      />.
    iceSculpting: Ujděte <numberProgress current="{current}" max="{max}" /> kroků
      během aktivity <object id="activity-ice_sculpting-2b0be0f5-69d5-4205-922d-c5a02c056cab"
      alwaysShow="true" /> v <object id="location-frusenholm-5ddb0735-4582-4858-80a0-7489f1b043a2"
      alwaysShow="true" />.
    underwaterBasketweaving: Ujděte <numberProgress current="{current}" max="{max}"
      /> kroků během aktivity <object id="activity-underwater_basket_weaving-7ba725a2-d147-437c-98bf-5a9f58d68b65"
      alwaysShow="true" /> v <object id="location-fertile_shallows-6561e4b5-fce3-4307-a641-86ca5aee36d6"
      alwaysShow="true" />.
    sledding: Během aktivity <object id="activity-sledding-290bfd6c-3bb1-47c6-bf60-880c1d4a5148"
      />.
  haveItemStack:
    text: Mějte zásobu položek <object id="{obj}" alwaysShow="true" /> o velikosti
      <numberProgress current="{current}" max="{max}" />.
  exploreRealm:
    text: Prozkoumejte kompletně <object id="{obj}" alwaysShow="true" />. <numberProgress
      current="{current}" max="{max}" />.
  locationHasKeywords:
    text: Během v místě <object id="{obj}" />.
  factionReputations:
    jarvoniaReputation: Mějte pověst frakce <numberProgress current="{current}" max="{max}"
      /> <realm realm="faction-jarvonia-1b061315-a63d-4dc1-a8ba-10902a83c5db" />.
    syrenthiaReputation: Mějte pověst frakce <numberProgress current="{current}" max="{max}"
      /> <realm realm="faction-syrenthia-6e9359fa-597b-4448-9df5-cc3fff9a5108" />.
    trellinReputation: Mějte pověst frakce <numberProgress current="{current}" max="{max}"
      /> <realm realm="faction-trellin-239a0ad8-3812-4f2a-9c11-1c312490249b" />.
    erdwiseReputation: Mějte pověst frakce <numberProgress current="{current}" max="{max}"
      /> <realm realm="faction-erdwise-697ae8a6-491e-46fd-8a05-4b744f9630eb" />.
    halflingRebelsReputation: Mějte pověst frakce <numberProgress current="{current}"
      max="{max}" /> <realm realm="faction-halfling_rebels-394eaff8-2749-4473-949c-80da531a415e"
      />.
