singulars:
  mainSkill:
    text: Tegeledes oskusega <skill skill="{skill}"/>
  skillLevel:
    text: Vähemalt <skill skill="{skill}" level="{level}" needed/>
  traveling:
    text: Rännates
  itemAnywhereWithYou:
    text: Vajalik <item id="{item}"/>.
  itemEquipped:
    text: Kasutusel vajalik <item id="{item}"/>.
  itemInInventory:
    text: Kaasas vajalik <item id="{item}"/>.
  itemAnywhere:
    text: Vajalik <item id="{item}"/>.
  distinctItemsEquippedKeyword:
    text: Kasutusel <numberProgress current="{current}" max="{max}" /> <object id="{obj}"
      />.
  totalSteps:
    text: Kokku kõnnitud <numberProgress current="{current}" max="{max}" /> sammu.
  characterLevel:
    text: Karakteri tase <numberProgress current="{current}" max="{max}" />.
  unlocked:
    text: Avatud <object id="{obj}" alwaysShow="true" />.
  achievementPoints:
    text: <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> saavutuspunkti.
  achievementPointsPercent:
    text: <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> saavutuspunkti ({percentage}% koguarvust).
  haveCoins:
    text: Oma <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> kulda.
  minimumSkillLevel:
    text: Kõik tasemed vähemalt <numberProgress current="{current}" max="{max}" />.
  levelUpSkills:
    text: Suurenda oma oskuste taset <numberProgress current="{current}" max="{max}"
      /> korda.
  overencumbered:
    text: Paki seljakotti rohkem kui kanda jaksad.
  haveItemStack:
    text: Oma eseme <object id="{obj}" alwaysShow="true" /> kuhja, mille suurus on
      <numberProgress current="{current}" max="{max}" />.
  exploreRegion:
    text: Avasta <object id="{obj}" alwaysShow="true" /> täielikult. <numberProgress
      current="{current}" max="{max}" />.
  haveBankStacks:
    text: Oma pangas <numberProgress current="{current}" max="{max}" /> esemekuhja.
  activityType:
    singleKeyword: Tehes tegevust <object id="{obj}" />.
  service:
    text: Vajalik vähemalt teenus <serviceTier tier="{tier}" /> <object id="{obj}"
      />.
  realm:
    text: Olles asukohas <realm realm="{realm}" />.
  locationHasKeywords:
    text: Olles <object id="{obj}" /> asukohas.
  uniques:
    intermediateCrossCountry: Tegele Keskastme Murdmaasuusatamisega <numberProgress
      current="{current}" max="{max} /> korda.
    firewoodMaking: Tegele Küttepuude Tegemisega <numberProgress current="{current}"
      max="{max} /> korda.
    woodCarving: Tegele Puidust Nikerdamisega <numberProgress current="{current}"
      max="{max} /> korda.
    searchTeam: Osale Musta Silma Mäetipu Otsingurühmas <numberProgress current="{current}"
      max="{max} /> korda.
    intermediateShipRepair: Tegele Keskastme Laevaparandusega <numberProgress current="{current}"
      max="{max} /> korda.
    beginnerCrossCountry: Tegele Algaja Murdmaasuusatamisega <numberProgress current="{current}"
      max="{max} /> korda.
  factionReputations:
    jarvoniaReputation: <numberProgress current="{current}" max="{max}" /> <realm
      realm="faction-jarvonia-1b061315-a63d-4dc1-a8ba-10902a83c5db" /> kildkonna reputatsioon.
    syrenthiaReputation: <numberProgress current="{current}" max="{max}" /> <realm
      realm="faction-syrenthia-6e9359fa-597b-4448-9df5-cc3fff9a5108" /> kildkonna
      reputatsioon.
    trellinReputation: <numberProgress current="{current}" max="{max}" /> <realm realm="faction-trellin-239a0ad8-3812-4f2a-9c11-1c312490249b"
      /> kildkonna reputatsioon.
    erdwiseReputation: <numberProgress current="{current}" max="{max}" /> <realm realm="faction-erdwise-697ae8a6-491e-46fd-8a05-4b744f9630eb"
      /> kildkonna reputatsioon.
