singulars:
  smithing:
    basicForge:
      name: Algne Sepikoda
      desc: Algaja sepa töökoda, ideaalne lihtsate esemete valmistamiseks.
    advancedForge:
      name: Edasijõudnud Sepikoda
      desc: Kõrgetasemeline ääs, sobiv keerukate ja kõrgkvaliteediliste loomingute
        jaoks.
    frozenForge:
      name: Jäätunud Sepikoda
      desc: Jääst tahutud ääs, kaetud pingviine kujutavate nikerdustega.
    underwaterForge:
      name: Veealune Sepikoda (Algne)
      desc: See veealune sepatöökoda toimib tänu kuumadele aurugeisritele, mis pakuvad
        piisavalt kuumust, et sulatada metalli.
  cooking:
    basicKitchen:
      name: Algne Köök
      desc: Tagasihoidlik köögiplaan, kus saad vaaritada lihtsaid, kosutavaid ja tervislikke
        toitusid.
    advancedKitchen:
      name: Edasijõudnud Köök
      desc: Hästi varustatud köök, sobilik gurmeekokanduseks ja kulinaarseteks eksperimentideks.
    underwaterKitchen:
      name: Veealune Köök (Algne)
      desc: Köök on varustatud mitmesuguste kulinaariariistadega, mis on sobilikud
        veealuseks toiduvalmistaseks.
    eberhartMansionKitchen:
      name: Eberharti Mõisa Köök (Edasijõudnud)
      desc: Eberharti perekond annab neile, kes annavad teistele. Tõestus sinu pühandumusest
        kohalikule supiköögile on rohkem kui piisav põhjus neile, et oma uksed avada
        ja aidata sind nende ühisköögis.
    azurazeraKitchen:
      name: Alighti Köök (Algne)
      desc: Ühiskondlik köök – siin jagavad mitmed kokad kogemusi, et teineteist kokakunstis
        arendada.
  crafting:
    basicWorkshop:
      name: Algne Töökoda
      desc: Baastasemel töökojaplaan - disainitud lihtsate ja praktiliste esemete
        meisterdamiseks.
    advancedWorkshop:
      name: Edasijõudnud Töökoda
      desc: Edasijõudnud töötsehh, varustatud kompleksete ja paindlike loomingute
        meisterdamiseks.
    tidalWorkshop:
      name: Lainealune Töökoda (Edasijõudnud)
      desc: Töökoda, mida alalõpmata mõjutab hoovus. Siin leiduvad kõik vajalikud
        tööriistad loomingu jaoks.
  carpentry:
    basicSawmill:
      desc: Algeline puidutöötlusrajatis, kus halud muudetakse standardseteks laudadeks.
      name: Algne Saeveski
    advancedSawmill:
      desc: Edasijõudnud puidutöötluse veski, suuteline looma täpsuse ja efektiivsusega
        kõrgekvaliteedilist saematerjali.
      name: Edasijõudnud Saeveski
    barbantokSawmill:
      name: Barbantoki Saeveski (Algne)
      desc: Saekaater, mida väidetavalt kummitab Barbantoki kummitus, legendaarne
        tisler, kes oli tuntud oma erakordse meisterlikkuse poolest.
    underwaterSawmill:
      name: Veealune Saeveski (Algne)
      desc: Saeveski, mis on täiuslik tööks puidutaoliste korallidega, aga pakub ka
        tööriistu halgude laudadeks tahumiseks.
    sawInHalfMill:
      name: Sae-poole saekaater (Edasijõudnud)
      desc: See kääbikute saeveski on inseneriteaduse ime, põhinedes veevoolul läbi
        veealuse akvedukti ja keerukal vesiveskil.
  cosmetics:
    barber:
      name: Juuksur
      desc: Juuksur, kes võib muuta su soengut teistsuguseks.
    wardrobe:
      name: Garderoob
      desc: Liigipääs sinu riidekapile, et saaksid muuta ome välimuste eri dekoratiivsete
        esemetaga, mida omad.
  tailoring:
    basicLoom:
      name: Algsed Kangasteljed
      desc: Tagasihoidlik töökoda, siin leiduvad toekad kangasteljed ning kulunud
        õmbluslaud. Näha on assortiid riidematerjale ja tööriistu - ideaalne virguvatele
        rätsepatele, et õppida riideloomiskunsti.
    advancedLoom:
      name: Edasijõudnud Kangasteljed
      desc: Hästi varustatud töökoda, näha on elegantne õmbluslaud ning siin olevad
        kangasteljed on tehnika viimane sõna. Koda on täis preemiumklassi kangaid
        ja spetsiaalseid tööriistu – ideaalne kogenenud rätsepale oivaliste rõivaste
        loomiseks.
  trinketry:
    basicTrinketryBench:
      name: Algne Juveliiritöö Pink
      desc: Tööpink, disainitud vääriskivide lõikamiseks ja lihtsate iluasjade valmistamiseks.
    ruinedTrinketryBench:
      name: Hävinud Juveliiritöö Pink (Algne)
      desc: Talve Ääre varemetes istub iidne juveliiritöö pink, kaetud sambla ja seentega.
    advancedTrinketryBench:
      name: Edasijõudnud Juveliiritöö Pink
      desc: Tagasihoidlik pink, täis läätsi, liivapaberit ja muid kogenud juveliirile
        sobilikke tööriistu.
    erdwissTrinketryFactory:
      name: Erdwissi Juveelivabrik (Edasijõudnud)
      desc: EJV võib kiidelda peeneimate vääriskivide lõikamise masinatega, imporditud
        otse Iiliääsist.
maps:
  tiers:
    "basic": Algne
    "advanced": Edasijõudnud
    "legendary": Legendaarne
    "mythic": Müütiline
