singulars:
  smithing:
    basicForge:
      name: Algne Sepikoda
      desc: Algaja sepa töökoda, ideaalne lihtsate esemete valmistamiseks.
    advancedForge:
      name: Edasijõudnud Sepikoda
      desc: Kõrgetasemeline ääs, sobiv keerukate ja kõrgkvaliteediliste loomingute
        jaoks.
    frozenForge:
      name: Jäätunud Sepikoda
      desc: Jääst tahutud ääs, kaetud pingviine kujutavate nikerdustega.
    underwaterForge:
      name: Veealune Sepikoda (Algne)
      desc: See veealune sepatöökoda toimib tänu kuumadele aurugeisritele, mis pakuvad
        piisavalt kuumust, et sulatada metalli.
  cooking:
    basicKitchen:
      name: Algne Köök
      desc: Tagasihoidlik köögiplaan, kus saad vaaritada lihtsaid, kosutavaid ja tervislikke
        toitusid.
    advancedKitchen:
      name: Edasijõudnud Köök
      desc: Hästi varustatud köök, sobilik gurmeekokanduseks ja kulinaarseteks eksperimentideks.
    underwaterKitchen:
      name: Veealune Köök (Algne)
      desc: Köök on varustatud mitmesuguste veealuseks toiduvalmistaseks sobilike
        kulinaariariistadega.
    eberhartMansionKitchen:
      name: Eberharti Mõisa Köök (Edasijõudnud)
      desc: Eberharti perekond annab neile, kes annavad teistele. Tõestus sinu pühandumusest
        kohalikule supiköögile on rohkem kui piisav põhjus neile, et oma uksed avada
        ja lasta sul kasutada nende ühiskööki.
  crafting:
    basicWorkshop:
      name: Algne Töökoda
      desc: Baastasemel töökojaplaan - disainitud lihtsate ja praktiliste esemete
        meisterdamiseks.
    advancedWorkshop:
      name: Edasijõudnud Töökoda
      desc: Edasijõudnud töötsehh, varustatud kompleksete ja paindlike loomingute
        meisterdamiseks.
    tidalWorkshop:
      name: Lainealune Töökoda (Edasijõudnud)
      desc: Töökoda, mida alalõpmata mõjutab hoovus. Siin leiduvad kõik vajalikud
        tööriistad loomingu jaoks.
  carpentry:
    basicSawmill:
      desc: Algeline puidutöötlusrajatis, kus halud muudetakse standardseteks laudadeks.
      name: Algne Saeveski
    advancedSawmill:
      desc: Edasijõudnud puidutöötluse veski, suuteline looma täpsuse ja efektiivsusega
        kõrgekvaliteedilist saematerjali.
      name: Edasijõudnud Saeveski
    barbantokSawmill:
      name: Barbantoki Saeveski (Algne)
      desc: Saekaater, mida väidetavalt kummitab Barbantoki kummitus, legendaarne
        tisler, kes oli tuntud oma erakordse meisterlikkuse poolest.
    underwaterSawmill:
      name: Veealune Saeveski (Algne)
      desc: Saeveski, mis on täiuslik tööks puidutaoliste korallidega, aga pakub ka
        tööriistu halgude laudadeks tahumiseks.
  cosmetics:
    barber:
      name: Juuksur
      desc: Juuksur, kes võib muuta su soengut teistsuguseks.
    wardrobe:
      name: Garderoob
      desc: Liigipääs sinu riidekapile, et saaksid muuta ome välimuste eri dekoratiivsete
        esemetaga, mida omad.
maps:
  tiers:
    "basic": Algne
    "advanced": Edasijõudnud
    "legendary": Legendaarne
    "mythic": Müütiline
