singulars:
  mainSkill:
    text: Während der Ausführung von <skill skill="{skill}"/>.
  skillLevel:
    text: Mindestens <skill skill="{skill}" level="{level}" notwendig/>.
  traveling:
    text: Während dem Reisen.
  itemAnywhereWithYou:
    text: Habe <item id="{item}"/> bei dir.
  itemEquipped:
    text: Habe <item id="{item}"/> ausgerüstet.
  itemInInventory:
    text: Habe <item id="{item}"/> in deinem Inventar.
  itemAnywhere:
    text: Besitze <item id="{item}"/>.
  distinctItemsEquippedKeyword:
    text: Erfordert <numberProgress current="{current}" max="{max}" /> einzigartig
      ausgerüstete <object id="{obj}" />.
  totalSteps:
    text: Sei <numberProgress current="{current}" max="{max}" /> Schritte gelaufen.
  characterLevel:
    text: Habe Charakterlevel <numberProgress current="{current}" max="{max}" />.
  unlocked:
    text: Hab <object id="{obj}" alwaysShow="true" /> freigeschaltet.
  achievementPoints:
    text: Habe <icon i="achievement point"/><numberProgress current="{current}" max="{max}"
      /> Erfolgspunkte.
  achievementPointsPercent:
    text: Habe <icon i="achievement point"/><numberProgress current="{current}" max="{max}"
      /> Erfolgspunkte ({percentage}% des gesamten).
  haveCoins:
    text: Habe <icon i="money small"/><numberProgress current="{current}" max="{max}"
      /> Münzen.
  minimumSkillLevel:
    text: Habe alle Skills mindestens auf Level <numberProgress current="{current}"
      max="{max}" />.
  levelUpSkills:
    text: Steigere deine Fertigkeiten <numberProgress current="{current}" max="{max}"
      /> Mal.
  overencumbered:
    text: Sei über dem Inventarlimit (überladen).
  exploreRegion:
    text: Erkunde <object id="{obj}" alwaysShow="true" /> vollständig. <numberProgress
      current="{current}" max="{max}" />.
  haveBankStacks:
    text: Habe <numberProgress current="{current}" max="{max}" /> Gegenstandsstapel
      in deiner Bank.
  activityType:
    singleKeyword: Während einer <object id="{obj}" /> Aktivität.
  service:
    text: Braucht <serviceTier tier="{tier}" /> <object id="{obj}" /> Service oder
      besser.
  realm:
    text: Während du in <realm realm="{realm}" /> bist.
  uniques:
    firewoodMaking: Beende die <object id="activity-firewood_making-407263a4-4ee1-4383-a624-2a7ed70c4b10"
      alwaysShow="true" /> Aktivität <numberProgress current="{current}" max="{max}"
      /> mal.
    woodCarving: Beende die<object id="activity-wood_carving-af675674-c972-4e2e-80fe-1501b972e353"
      alwaysShow="true" /> Aktivität <numberProgress current="{current}" max="{max}"
      /> mal.
    searchTeam: Beende die Schwarzaugen-Gipfel <object id="activity-black_eye_peak_search_team-d1ad835f-0898-4fc7-8f0a-4b0626d95306"
      alwaysShow="true" /> Aktivität am <object id="location-horn_of_respite-1661d247-11f1-49eb-b927-6e59c8fd7774"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> mal.
    intermediateShipRepair: Beende die <object id="activity-ship_repair_(intermediate)-44f2f2e7-bef1-437f-ac35-bf64b97cc249"
      alwaysShow="true" /> Aktivität <numberProgress current="{current}" max="{max}"
      /> mal.
    beginnerCrossCountry: Beende die <object 
      id="activity-cross-country_skiing_(beginner)-fc421940-d63a-402f-aa50-26cc2efea4d3"
      alwaysShow="true" /> Aktivität <numberProgress current="{current}" max="{max}"
      /> mal.
    intermediateCrossCountry: Beende die <object 
      id="activity-cross-country_skiing_(intermediate)-42788047-6cc3-4711-88be-999e9504fc2a"
      alwaysShow="true" /> Aktivität <numberProgress current="{current}" max="{max}"
      /> mal.
    wreckDiving: Schließe die <object id="activity-wreck_diving-12e980cd-058a-42c4-8358-ba7afe1c319c"
      alwaysShow="true" /> Aktivität <numberProgress current="{current}" max="{max}"
      /> Male ab.
    wraithwaterBankRebuild: <object id="2808f754-9d31-4243-a711-7214a2a1c7b7" alwaysShow="true"
      />.
  factionReputations:
    jarvoniaReputation: Besitze <numberProgress current="{current}" max="{max}" />
      <realm realm="faction-jarvonia-1b061315-a63d-4dc1-a8ba-10902a83c5db" /> Fraktionsruf.
    trellinReputation: Besitze <numberProgress current="{current}" max="{max}" />
      <realm realm="faction-trellin-239a0ad8-3812-4f2a-9c11-1c312490249b" /> Fraktionsruf.
    erdwiseReputation: Besitze <numberProgress current="{current}" max="{max}" />
      <realm realm="faction-erdwise-697ae8a6-491e-46fd-8a05-4b744f9630eb" /> Fraktionsruf.
    syrenthiaReputation: Besitze <numberProgress current="{current}" max="{max}" />
      <realm realm="faction-syrenthia-6e9359fa-597b-4448-9df5-cc3fff9a5108" /> Fraktionsruf.
    halflingRebelsReputation: Besitze <numberProgress current="{current}" max="{max}"
      /> <realm realm="faction-halfling_rebels-394eaff8-2749-4473-949c-80da531a415e"
      /> Fraktionsruf.
  haveItemStack:
    text: Habe einen <object id="{obj}" alwaysShow="true" /> Stapel mit der Größe
      von <numberProgress current="{current}" max="{max}" />.
  locationHasKeywords:
    text: Während du in <object id="{obj}" /> bist.
  gear:
    tinkering: Habe die Aktivität <object id="activity-tinkering-cb2a8773-06d0-4661-9708-2bef5768119e"
      /> <numberProgress current="{current}" max="{max}" />-mal in <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a"
      alwaysShow="true" /> abgeschlossen.
    iceSculpting: Habe die Aktivität <object id="activity-ice_sculpting-2b0be0f5-69d5-4205-922d-c5a02c056cab"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" />-mal
      in <object id="location-frusenholm-5ddb0735-4582-4858-80a0-7489f1b043a2" alwaysShow="true"
      /> abgeschlossen.
    swimmingExpert: Habe die <object id="activity-swimming_(expert)-95a78afb-79f0-431c-b7aa-062659d9ec87"
      alwaysShow="true" /> Aktivität <numberProgress current="{current}" max="{max}"
      /> mal beendet.
    underwaterBasketweaving: Habe die Aktivität <object id="activity-underwater_basket_weaving-7ba725a2-d147-437c-98bf-5a9f58d68b65"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" />-mal
      in <object id="location-fertile_shallows-6561e4b5-fce3-4307-a641-86ca5aee36d6"
      alwaysShow="true" /> abgeschlossen.
    beginnerSkydisc: Habe die <object id="activity-frisbee_golfing_(beginner)-0fb41f4d-f46b-4a6d-acdf-f2525654c714"
      alwaysShow="true" /> Aktivität in <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> mal
      abgeschlossen.
    sledding: Während der Aktivität <object id="activity-sledding-290bfd6c-3bb1-47c6-bf60-880c1d4a5148"
      />.
  exploreRealm:
    text: Erforsche <object id="{obj}" alwaysShow="true" /> vollends. <numberProgress
      current="{current}" max="{max}" />.
  maps:
    jarvoniaMap: Besitze eine <object id="item-map_of_jarvonia-86ba96b3-a845-4f5c-a054-04ec5146fb25"
      />.
    syrenthiaMap: Besitze eine <object id="65979ee2-f98a-41c3-9f12-8858000017a3" />.
    trellinMap: Besitze eine <object id="item-map_of_gdte-b28951b2-2cac-4e53-b6f1-bc2030590433"
      />.
    erdwiseMap: Besitze eine <object id="fa277527-585b-4a1d-bc73-a25fe1195017" />.
    halflingMap: Besitze eine <object id="f1a9e370-fd69-4a49-92c0-c83475a896ab" />.
  itemQualityEquipped:
    withoutType: Habe mindestens <numberProgress current="{current}" max="{max}" /><itemQuality
      quality="{quality}" type="crafted"/> oder <itemQuality quality="{quality}" type="loot"/>
      Gegenstände ausgerüstet.
    text: Habe mindestens <numberProgress current="{current}" max="{max}" /> <itemQuality
      quality="{quality}" type="{type}"/>-Gegenstände ausgerüstet.
  keywordEquipped:
    text: Habe <object id="{obj}" /> ausgerüstet.
  mainSkillType:
    text: Während der Ausführung von <skillType type="{type}"/> Fähigkeiten.
  keywordWithLevelEquipped:
    text: Habe <object id="{obj}" /> ausgerüstet, das mindestens <skill skill="{skill}"/>-Stufe
      <numberProgress current="{current}" max="{max}" /> erfordert.
  totalSkillLevel:
    text: Besitze eine Gesamtlevel von <numberProgress current="{current}" max="{max}"
      />.
  petWithKeyword:
    textDistinct: Besitze einzigartige <object id="{obj}" />-Haustiere. <numberProgress
      current="{current}" max="{max}" />.
    text: Besitze <object id="{obj}" />-Haustiere. <numberProgress current="{current}"
      max="{max}" />.
  itemsGained:
    text: Erlange <object id="{obj}" />. <numberProgress current="{current}" max="{max}"
      />.
  abilityAvailable:
    text: Während die Fähigkeit <object id="{obj}" /> verfügbar ist.
  hasPet:
    text: Besitze ein <object id="{obj}" /> Haustier.
  petAmount:
    text: Besitze <numberProgress current="{current}" max="{max}" /> Haustiere.
  petTotalLevels:
    text: Besitze insgesamt <numberProgress current="{current}" max="{max}" /> Haustierlevel
      über alle Haustiere hinweg.
  petHighestLevel:
    text: Besitze ein Haustier mit mindestens Level <numberProgress current="{current}"
      max="{max}" />.
  itemsWithKeywordCrafted:
    text: Habe <object id="{obj}" />-Gegenstände hergestellt. <numberProgress current="{current}"
      max="{max}" />.
  serviceKeywords:
    text: Benötigt <serviceTier tier="{tier}" /> {objects} Service oder besser.
