singulars:
  mainSkill:
    text: While doing <skill skill="${skill}"/>
  skillLevel:
    text: At least <skill skill="${skill}" level="${level}" needed/>
  traveling:
    text: While travelling
  itemAnywhereWithYou:
    text: Have item <item id="${item}"/> with you.
  itemEquipped:
    text: Have item <item id="${item}"/> equipped.
  itemInInventory:
    text: Have item <item id="${item}"/> in your inventory.
  itemAnywhere:
    text: Have item <item id="${item}"/> owned by you, either in inventory or bank.
  totalSteps:
    text: Have <numberProgress current="${current}" max="${max}" /> steps walked in total.
  characterLevel:
    text: Have character level <numberProgress current="${current}" max="${max}" />.
  unlocked:
    text: Have unlocked <object id="${obj}">.