singulars:
  traveling:
    text: Ceļošanas laikā
  itemInInventory:
    text: Ir priekšmets <item id="{item}"/> tavā Inventārā.
  itemAnywhere:
    text: Ir priekšmets <item id="{item}"/>.
  totalSteps:
    text: Kopā ir noieti <numberProgress current="{current}" max="{max}" /> soļi.
  unlocked:
    text: Ir atbloķēts <object id="{obj}" alwaysShow="true" />.
  achievementPoints:
    text: Ir <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> sasniegumu punkti.
  haveCoins:
    text: Ir <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> monētas.
  minimumSkillLevel:
    text: Katrai prasmei jābūt vismaz <numberProgress current="{current}" max="{max}"
      /> līmenim.
  levelUpSkills:
    text: Uzlabo savas prasmes <numberProgress current="{current}" max="{max}" />
      reizes.
  overencumbered:
    text: Tavs inventārs pārsniedz limitu (pārāk apgrūtināts).
  mainSkill:
    text: Veicot <skill skill="{skill}"/>
  itemAnywhereWithYou:
    text: Ir priekšmets <item id="{item}"/> ar tevi.
  achievementPointsPercent:
    text: Ir <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> sasniegumu punkti ({percentage}% no kopējā skaita).
  characterLevel:
    text: Ir varoņa līmenis <numberProgress current="{current}" max="{max}" />.
