singulars:
  traveling:
    text: Ceļošanas laikā
  itemInInventory:
    text: Ir priekšmets <item id="{item}"/> tavā Inventārā.
  itemAnywhere:
    text: Ir priekšmets <item id="{item}"/>.
  totalSteps:
    text: Kopā ir noieti <numberProgress current="{current}" max="{max}" /> soļi.
  unlocked:
    text: Ir atbloķēts <object id="{obj}" alwaysShow="true" />.
  achievementPoints:
    text: Ir <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> sasniegumu punkti.
  haveCoins:
    text: Ir <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> monētas.
  minimumSkillLevel:
    text: Katrai prasmei jābūt vismaz <numberProgress current="{current}" max="{max}"
      /> līmenim.
  levelUpSkills:
    text: Uzlabo savas prasmes <numberProgress current="{current}" max="{max}" />
      reizes.
  overencumbered:
    text: Tavs inventārs pārsniedz limitu (pārāk apgrūtināts).
  mainSkill:
    text: Veicot <skill skill="{skill}"/>
  itemAnywhereWithYou:
    text: Ir priekšmets <item id="{item}"/> ar tevi.
  achievementPointsPercent:
    text: Ir <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> sasniegumu punkti ({percentage}% no kopējā skaita).
  characterLevel:
    text: Ir varoņa līmenis <numberProgress current="{current}" max="{max}" />.
  skillLevel:
    text: Nepieciešams vismaz <skill skill="{skill}" level="{level}"/>
  exploreRealm:
    text: Pilnībā izpētīt <object id="{obj}" alwaysShow="true" />. <numberProgress
      current="{current}" max="{max}" />.
  activityType:
    singleKeyword: Veicot aktivitāti <object id="{obj}" />.
  gear:
    tinkering: Ir veikti <numberProgress current="{current}" max="{max}" /> soļi attiecībā
      uz <object id="activity-tinkering-cb2a8773-06d0-4661-9708-2bef5768119e" /> aktivitāti
      <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a" alwaysShow="true"
      />.
    beginnerSkydisc: Esmu pabeidzis <object id="activity-frisbee_golfing_(beginner)-0fb41f4d-f46b-4a6d-acdf-f2525654c714"
      alwaysShow="true" /> aktivitāti <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> reižu.
    iceSculpting: Ir veikti <numberProgress current="{current}" max="{max}" /> soļi
      <object id="activity-ice_sculpting-2b0be0f5-69d5-4205-922d-c5a02c056cab" alwaysShow="true"
      /> aktivitātē <object id="location-frusenholm-5ddb0735-4582-4858-80a0-7489f1b043a2"
      alwaysShow="true" />.
    swimmingExpert: Ir pabeigtas <object id="activity-swimming_(expert)-95a78afb-79f0-431c-b7aa-062659d9ec87"
      alwaysShow="true" /> aktivitātes <numberProgress current="{current}" max="{max}"
      /> reizes.
    underwaterBasketweaving: Ir veikti <numberProgress current="{current}" max="{max}"
      /> soļi <object id="activity-underwater_basket_weaving-7ba725a2-d147-437c-98bf-5a9f58d68b65"
      alwaysShow="true" /> aktivitātē <object id="location-fertile_shallows-6561e4b5-fce3-4307-a641-86ca5aee36d6"
      alwaysShow="true" />.
    sledding: Veicot <object id="activity-sledding-290bfd6c-3bb1-47c6-bf60-880c1d4a5148"
      />aktivitāti.
  uniques:
    searchTeam: Pabeidz Melnās acs kalna <object id="activity-black_eye_peak_search_team-d1ad835f-0898-4fc7-8f0a-4b0626d95306"
      alwaysShow="true" /> aktivitāti <object id="location-horn_of_respite-1661d247-11f1-49eb-b927-6e59c8fd7774"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> reižu.
    intermediateShipRepair: Pabeidz <object id="activity-ship_repair_(intermediate)-44f2f2e7-bef1-437f-ac35-bf64b97cc249"
      alwaysShow="true" /> aktivitāti <numberProgress current="{current}" max="{max}"
      /> reizes.
  factionReputations:
    syrenthiaReputation: Ir <numberProgress current="{current}" max="{max}" /> <realm
      realm="faction-syrenthia-6e9359fa-597b-4448-9df5-cc3fff9a5108" /> frakcijas
      reputācija.
    halflingRebelsReputation: Ir <numberProgress current="{current}" max="{max}" />
      <realm realm="faction-halfling_rebels-394eaff8-2749-4473-949c-80da531a415e"
      /> frakcijas reputācija.
    jarvoniaReputation: Ir <numberProgress current="{current}" max="{max}" /> <realm
      realm="faction-jarvonia-1b061315-a63d-4dc1-a8ba-10902a83c5db" /> frakcijas reputācija.
    trellinReputation: Ir <numberProgress current="{current}" max="{max}" /> <realm
      realm="faction-trellin-239a0ad8-3812-4f2a-9c11-1c312490249b" /> frakcijas reputācija.
    erdwiseReputation: Ir <numberProgress current="{current}" max="{max}" /> <realm
      realm="faction-erdwise-697ae8a6-491e-46fd-8a05-4b744f9630eb" /> frakcijas reputācija.
  realm:
    text: Atrodoties apgabalā <realm realm="{realm}" />.
  maps:
    jarvoniaMap: Pieder <object id="item-map_of_jarvonia-86ba96b3-a845-4f5c-a054-04ec5146fb25"
      />.
    syrenthiaMap: Pieder <object id="65979ee2-f98a-41c3-9f12-8858000017a3" />.
    trellinMap: Pieder <object id="e73f9ab8-04e9-49c9-8fd4-d325fbc360e8" />.
    erdwiseMap: Pieder <object id="fa277527-585b-4a1d-bc73-a25fe1195017" />.
    halflingMap: Pieder <object id="f1a9e370-fd69-4a49-92c0-c83475a896ab" />.
