singulars:
  levelUpSkills:
    text: Awansuj poziomy umiejętności <numberProgress current="{current}" max="{max}"
      /> razy.
  skillLevel:
    text: Wymaga przynajmniej <skill skill="{skill}" level="{level}"/>
  itemAnywhere:
    text: Posiadaj przedmiot <item id="{item}"/>.
  traveling:
    text: W trakcie podróży
  itemAnywhereWithYou:
    text: Miej przedmiot <item id="{item}"/> przy sobie.
  itemEquipped:
    text: Miej założony przedmiot <item id="{item}"/>.
  itemInInventory:
    text: Miej przedmiot <item id="{item}"/> w ekwipunku.
  distinctItemsEquippedKeyword:
    text: Miej <numberProgress current="${current}" max="${max}" /> z <object id="${obj}"
      /> założone.
  characterLevel:
    text: Miej postać o poziomie <numberProgress current="{current}" max="{max}" />.
  unlocked:
    text: Odblokuj <object id="{obj}" alwaysShow="true" />.
  achievementPointsPercent:
    text: Miej <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> Punktów Osiągnięć ({percentage}% wszystkich).
  haveCoins:
    text: Miej <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> monet.
  minimumSkillLevel:
    text: Miej wszystkie umiejętności na przynajmniej <numberProgress current="{current}"
      max="{max}" /> poziomie.
  overencumbered:
    text: Miej więcej przedmiotów niż limit ekwipunku (przeciążenie).
  haveItemStack:
    text: Miej pole ekwipunku <object id="{obj}" alwaysShow="true" /> wielkości <numberProgress
      current="{current}" max="{max}" /> sztuk.
  haveBankStacks:
    text: Miej <numberProgress current="{current}" max="{max}" /> stacków przedmiotów
      w swoim banku.
  activityType:
    singleKeyword: W trakcie wykonywania <object id="{obj}" />.
  service:
    text: Wymaga usługi <serviceTier tier="{tier}" /> <object id="{obj}" /> lub lepszej.
  realm:
    text: Będąc w <realm realm="{realm}" />.
  locationHasKeywords:
    text: Będąc w <object id="{obj}" />.
  uniques:
    intermediateShipRepair: Ukończ aktywność Naprawa Statku (Zaawansowany) <numberProgress
      current="{current}" max="{max} /> razy.
    firewoodMaking: Ukończ aktywność Rozpalanie Ognia <numberProgress current="{current}"
      max="{max} /> razy.
    intermediateCrossCountry: Ukończ aktywność Narciarstwo Biegowe (Zaawansowany)
      <numberProgress current="{current}" max="{max} /> razy.
    searchTeam: Ukończ aktywność Grupa Poszukiwawcza Szczyt Czarnego Oka <numberProgress
      current="{current}" max="{max} /> razy.
    woodCarving: Ukończ aktywność Rzeźbienie w Drewnie <numberProgress current="{current}"
      max="{max} /> razy.
    beginnerCrossCountry: Ukończ aktywność Narciarstwo Biegowe (Początkujący) <numberProgress
      current="{current}" max="{max} /> razy.
  factionReputations:
    jarvoniaReputation: <numberProgress current="{current}" max="{max}" /> reputacji
      w frakcji <realm realm="faction-jarvonia-1b061315-a63d-4dc1-a8ba-10902a83c5db"
      />.
    syrenthiaReputation: <numberProgress current="{current}" max="{max}" /> w frakcji
      <realm realm="faction-syrenthia-6e9359fa-597b-4448-9df5-cc3fff9a5108" />.
    erdwiseReputation: <numberProgress current="{current}" max="{max}" /> w frakcji
      <realm realm="faction-erdwise-697ae8a6-491e-46fd-8a05-4b744f9630eb" />.
    trellinReputation: <numberProgress current="{current}" max="{max}" /> w frakcji
      <realm realm="faction-trellin-239a0ad8-3812-4f2a-9c11-1c312490249b" /> faction
      reputation.
  mainSkill:
    text: W trakcie wykonywania <skill skill="{skill}"/>
  totalSteps:
    text: Miej <numberProgress current="{current}" max="{max}" /> ogólnie wykonanych
      kroków.
  achievementPoints:
    text: Miej <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> Punktów Osiągnięć.
  exploreRegion:
    text: Zwiedź obszar <object id="{obj}" alwaysShow="true" /> całkowicie. <numberProgress
      current="{current}" max="{max}" />.
