singulars:
  levelUpSkills:
    text: Awansuj poziomy umiejętności <numberProgress current="{current}" max="{max}"
      /> razy.
  skillLevel:
    text: Wymaga co najmniej <skill skill="{skill}" level="{level}" needed/>
  itemAnywhere:
    text: Posiadaj przedmiot <item id="{item}"/>.
  traveling:
    text: W trakcie podróży
  itemAnywhereWithYou:
    text: Miej przedmiot <item id="{item}"/> przy sobie.
  itemEquipped:
    text: Miej założony przedmiot <item id="{item}"/>.
  itemInInventory:
    text: Miej przedmiot <item id="{item}"/> w ekwipunku.
  distinctItemsEquippedKeyword:
    text: Wymaga <numberProgress current="{current}" max="{max}" /> wyposażonego <object
      id="{obj}" />.
  characterLevel:
    text: Miej postać o poziomie <numberProgress current="{current}" max="{max}" />.
  unlocked:
    text: Odblokuj <object id="{obj}" alwaysShow="true" />.
  achievementPointsPercent:
    text: Miej <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> Punktów Osiągnięć ({percentage}% wszystkich).
  haveCoins:
    text: Miej <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> monet.
  minimumSkillLevel:
    text: Miej wszystkie umiejętności na co najmniej <numberProgress current="{current}"
      max="{max}" /> poziomie.
  overencumbered:
    text: Miej więcej przedmiotów niż limit ekwipunku (przeciążenie).
  haveItemStack:
    text: Miej w ekwipunku stack <object id="{obj}" alwaysShow="true" /> wielkości
      <numberProgress current="{current}" max="{max}" /> sztuk.
  haveBankStacks:
    text: Miej <numberProgress current="{current}" max="{max}" /> stacków przedmiotów
      w swoim banku.
  activityType:
    singleKeyword: W trakcie wykonywania <object id="{obj}" />.
  service:
    text: Wymaga usługi <serviceTier tier="{tier}" /> <object id="{obj}" /> .
  realm:
    text: Będąc w obszarze <realm realm="{realm}" />.
  locationHasKeywords:
    text: Będąc w <object id="{obj}" />.
  uniques:
    intermediateShipRepair: Ukończ aktywność <object id="activity-ship_repair_(intermediate)-44f2f2e7-bef1-437f-ac35-bf64b97cc249"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> razy.
    firewoodMaking: Ukończ aktywność <object id="activity-firewood_making-407263a4-4ee1-4383-a624-2a7ed70c4b10"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> razy.
    intermediateCrossCountry: Ukończ aktywność <object 
      id="activity-cross-country_skiing_(intermediate)-42788047-6cc3-4711-88be-999e9504fc2a"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> razy.
    searchTeam: Ukończ aktywność na Szczycie Czarnego Oka <object id="activity-black_eye_peak_search_team-d1ad835f-0898-4fc7-8f0a-4b0626d95306"
      alwaysShow="true" /> w <object id="location-horn_of_respite-1661d247-11f1-49eb-b927-6e59c8fd7774"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> razy.
    woodCarving: Ukończ aktywność <object id="activity-wood_carving-af675674-c972-4e2e-80fe-1501b972e353"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> razy.
    beginnerCrossCountry: Ukończ aktywność <object 
      id="activity-cross-country_skiing_(beginner)-fc421940-d63a-402f-aa50-26cc2efea4d3"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> razy.
  factionReputations:
    jarvoniaReputation: Posiadaj <numberProgress current="{current}" max="{max}" />
      reputacji we frakcji <realm realm="faction-jarvonia-1b061315-a63d-4dc1-a8ba-10902a83c5db"
      />.
    syrenthiaReputation: Posiadaj <numberProgress current="{current}" max="{max}"
      /> reputacji we frakcji <realm realm="faction-syrenthia-6e9359fa-597b-4448-9df5-cc3fff9a5108"
      />.
    erdwiseReputation: Posiadaj <numberProgress current="{current}" max="{max}" />
      reputacji we frakcji <realm realm="faction-erdwise-697ae8a6-491e-46fd-8a05-4b744f9630eb"
      />.
    trellinReputation: Posiadaj <numberProgress current="{current}" max="{max}" />reputacji
      we frakcji <realm realm="faction-trellin-239a0ad8-3812-4f2a-9c11-1c312490249b"
      /> faction reputation.
    halflingRebelsReputation: Posiadaj <numberProgress current="{current}" max="{max}"
      /> reputacji we frakcji <realm realm="faction-halfling_rebels-394eaff8-2749-4473-949c-80da531a415e"
      />.
  mainSkill:
    text: W trakcie wykonywania <skill skill="{skill}"/>
  totalSteps:
    text: Miej <numberProgress current="{current}" max="{max}" /> ogólnie wykonanych
      kroków.
  achievementPoints:
    text: Miej <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> Punktów Osiągnięć.
  exploreRegion:
    text: Zwiedź obszar <object id="{obj}" alwaysShow="true" /> całkowicie. <numberProgress
      current="{current}" max="{max}" />.
  gear:
    beginnerSkydisc: Miej ukończoną aktywność <object id="activity-frisbee_golfing_(beginner)-0fb41f4d-f46b-4a6d-acdf-f2525654c714"
      alwaysShow="true" /> w <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> razy.
    tinkering: Miej ukończoną aktywność <object id="activity-tinkering-cb2a8773-06d0-4661-9708-2bef5768119e"
      /> <numberProgress current="{current}" max="{max}" /> w <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a"
      alwaysShow="true" /> razy
    iceSculpting: Miej ukończoną aktywność <object id="activity-ice_sculpting-2b0be0f5-69d5-4205-922d-c5a02c056cab"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> w <object
      id="location-frusenholm-5ddb0735-4582-4858-80a0-7489f1b043a2" alwaysShow="true"
      /> razy
    swimmingExpert: Miej ukończoną aktywność <object id="activity-swimming_(expert)-95a78afb-79f0-431c-b7aa-062659d9ec87"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> razy.
    underwaterBasketweaving: Miej ukończoną aktywność <object id="activity-underwater_basket_weaving-7ba725a2-d147-437c-98bf-5a9f58d68b65"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> w <object
      id="location-fertile_shallows-6561e4b5-fce3-4307-a641-86ca5aee36d6" alwaysShow="true"
      /> razy
    sledding: W trakcie wykonywania <object id="activity-sledding-290bfd6c-3bb1-47c6-bf60-880c1d4a5148"
      />.
  exploreRealm:
    text: Zbadaj całkowicie <object id="{obj}" alwaysShow="true" /> . <numberProgress
      current="{current}" max="{max}" />.
  maps:
    jarvoniaMap: Posiadaj <object id="item-map_of_jarvonia-86ba96b3-a845-4f5c-a054-04ec5146fb25"
      />.
    syrenthiaMap: Posiadaj <object id="65979ee2-f98a-41c3-9f12-8858000017a3" />.
    trellinMap: Posiadaj <object id="item-map_of_gdte-b28951b2-2cac-4e53-b6f1-bc2030590433"
      />.
    halflingMap: Posiadaj <object id="f1a9e370-fd69-4a49-92c0-c83475a896ab" />.
    erdwiseMap: Posiadaj <object id="fa277527-585b-4a1d-bc73-a25fe1195017" />.
