singulars:
  traveling:
    text: Matkustaessa.
  locationHasKeywords:
    text: Ollessasi paikassa <object id="{obj}" />.
  achievementPoints:
    text: Kerää <icon i="achievement point"/> <numberProgress current="{current}"
      max="{max}" /> saavutuspistettä.
  achievementPointsPercent:
    text: Kerää <icon i="achievement point"/><numberProgress current="{current}" max="{max}"
      /> saavutuspistettä ({percentage}% kokonaismäärästä).
  haveCoins:
    text: Kerää <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> rahaa.
  minimumSkillLevel:
    text: Saavuta jokaisessa taidossa vähintään taso <numberProgress current="{current}"
      max="{max}" />.
  levelUpSkills:
    text: Taitojen kokonaistason on oltava <numberProgress current="{current}" max="{max}"
      />.
  haveItemStack:
    text: Omista <object id="{obj}" alwaysShow="true" /> esineelle pino, jossa on
      esineitä vähintään <numberProgress current="{current}" max="{max}" />.
  exploreRegion:
    text: Tutki <object id="{obj}" alwaysShow="true" /> kokonaan. <numberProgress
      current="{current}" max="{max}" />.
  haveBankStacks:
    text: Pankissasi on <numberProgress current="{current}" max="{max}" /> esinepinoa
      tavaroita.
  activityType:
    singleKeyword: Tehdessäsi aktiviteettia <object id="{obj}" />.
  service:
    text: 'Edellytys: <serviceTier tier="{tier}" /> tai parempi <object id="{obj}"
      />.'
  realm:
    text: Ollessasi maassa <realm realm="{realm}" />
  uniques:
    woodCarving: Toista <object id="activity-wood_carving-af675674-c972-4e2e-80fe-1501b972e353"
      alwaysShow="true" />-aktiviteettia <numberProgress current="{current}" max="{max}"
      /> kertaa.
    intermediateShipRepair: Suorita <object id="activity-ship_repair_(intermediate)-44f2f2e7-bef1-437f-ac35-bf64b97cc249"
      alwaysShow="true" /> -aktiviteettia <numberProgress current="{current}" max="{max}"
      /> kertaa.
    firewoodMaking: Toista <object id="activity-firewood_making-407263a4-4ee1-4383-a624-2a7ed70c4b10"
      alwaysShow="true" /> -aktiviteettia <numberProgress current="{current}" max="{max}"
      /> kertaa.
    intermediateCrossCountry: Tee <object 
      id="activity-cross-country_skiing_(intermediate)-42788047-6cc3-4711-88be-999e9504fc2a"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> kertaa.
    beginnerCrossCountry: Tee <object 
      id="activity-cross-country_skiing_(beginner)-fc421940-d63a-402f-aa50-26cc2efea4d3"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> kertaa.
    searchTeam: Suorita Mustasilmähuipun <object id="activity-black_eye_peak_search_team-d1ad835f-0898-4fc7-8f0a-4b0626d95306"
      alwaysShow="true" /> -aktiviteetti kohteessa <object id="location-horn_of_respite-1661d247-11f1-49eb-b927-6e59c8fd7774"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> kertaa.
  factionReputations:
    syrenthiaReputation: Saavuta mainetaso <numberProgress current="{current}" max="{max}"
      /> ryhmittymässä <realm realm="faction-syrenthia-6e9359fa-597b-4448-9df5-cc3fff9a5108"
      />.
    trellinReputation: Saavuta mainetaso <numberProgress current="{current}" max="{max}"
      /> ryhmittymässä <realm realm="faction-trellin-239a0ad8-3812-4f2a-9c11-1c312490249b"
      />.
    erdwiseReputation: Saavuta mainetaso <numberProgress current="{current}" max="{max}"
      /> ryhmittymässä <realm realm="faction-erdwise-697ae8a6-491e-46fd-8a05-4b744f9630eb"
      />.
    jarvoniaReputation: Saavuta mainetaso <numberProgress current="{current}" max="{max}"
      /> ryhmittymässä <realm realm="faction-jarvonia-1b061315-a63d-4dc1-a8ba-10902a83c5db"
      />.
    halflingRebelsReputation: Saavuta <numberProgress current="{current}" max="{max}"
      /> mainetta ryhmittymässä <realm realm="faction-halfling_rebels-394eaff8-2749-4473-949c-80da531a415e"
      />.
  mainSkill:
    text: Kun suoritat taitoa <skill skill="{skill}"/>.
  skillLevel:
    text: Kehitä taitosi tasolle <skill skill="{skill}" level="{level}"needed/>.
  itemAnywhereWithYou:
    text: Esine <item id="{item}"/> on mukanasi.
  itemEquipped:
    text: Esine <item id="{item}"/> on puettuna.
  itemInInventory:
    text: Esine <item id="{item}"/> on repussasi.
  itemAnywhere:
    text: Omista <item id="{item}"/>.
  distinctItemsEquippedKeyword:
    text: Pidä <numberProgress current="{current}" max="{max}" /> erilaista kappaletta
      esinetyyppiä <object id="{obj}" /> puettuna.
  totalSteps:
    text: Kävele yhteensä <numberProgress current="{current}" max="{max}" /> askelta.
  characterLevel:
    text: Saavuta hahmon taso <numberProgress current="{current}" max="{max}" />.
  unlocked:
    text: Olen avannut lukituksen <object id="{obj}" alwaysShow="true" />.
  overencumbered:
    text: Ylitä reppusi kantoraja.
  gear:
    underwaterBasketweaving: <object id="activity-underwater_basket_weaving-7ba725a2-d147-437c-98bf-5a9f58d68b65"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> kertaa
      kohteessa <object id="location-fertile_shallows-6561e4b5-fce3-4307-a641-86ca5aee36d6"
      alwaysShow="true" />
    swimmingExpert: Toista <object id="activity-swimming_(expert)-95a78afb-79f0-431c-b7aa-062659d9ec87"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> kertaa.
    tinkering: <object id="activity-tinkering-cb2a8773-06d0-4661-9708-2bef5768119e"
      /> <numberProgress current="{current}" max="{max}" /> kertaa kohteessa <object
      id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a" alwaysShow="true"
      />
    iceSculpting: "Suorita seuraavia aktiviteetteja:\n<object id=\"activity-ice_sculpting-2b0be0f5-69d5-4205-922d-c5a02c056cab\"\
      \ alwaysShow=\"true\" /> <numberProgress current=\"{current}\" max=\"{max}\"\
      \ /> kertaa kohteessa <object id=\"location-frusenholm-5ddb0735-4582-4858-80a0-7489f1b043a2\"\
      \ alwaysShow=\"true\" />"
    beginnerSkydisc: Harjoittele aktiviteetilla <object id="activity-frisbee_golfing_(beginner)-0fb41f4d-f46b-4a6d-acdf-f2525654c714"
      alwaysShow="true" /> kohteessa <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> kertaa.
    sledding: Aktiviteetin <object id="activity-sledding-290bfd6c-3bb1-47c6-bf60-880c1d4a5148"
      /> aikana.
  exploreRealm:
    text: Tutki <object id="{obj}" alwaysShow="true" /> läpikotaisin. <numberProgress
      current="{current}" max="{max}" />.
  maps:
    syrenthiaMap: Hanki <object id="65979ee2-f98a-41c3-9f12-8858000017a3" />.
    trellinMap: Hanki <object id="item-map_of_gdte-b28951b2-2cac-4e53-b6f1-bc2030590433"
      />.
    halflingMap: Hanki <object id="f1a9e370-fd69-4a49-92c0-c83475a896ab" />.
    jarvoniaMap: Hanki <object id="item-map_of_jarvonia-86ba96b3-a845-4f5c-a054-04ec5146fb25"
      />.
    erdwiseMap: Hanki <object id="fa277527-585b-4a1d-bc73-a25fe1195017" />.
  mainSkillType:
    text: Kun käytät taitotyyppiä <skillType type="{type}"/>.
  itemQualityEquipped:
    text: Ylläsi on oltava vähintään <numberProgress current="{current}" max="{max}"
      /> esinettä, joiden laatu on <itemQuality quality="{quality}" type="{type}"/>.
    withoutType: Ylläsi on oltava vähintään <numberProgress current="{current}" max="{max}"
      /> esinettä, joiden laatu on <itemQuality quality="{quality}" type="crafted"/>,
      tai <itemQuality quality="{quality}" type="loot"/>.
  keywordEquipped:
    text: <object id="{obj}" /> on oltava käytössä.
  keywordWithLevelEquipped:
    text: Ylläsi on oltava <object id="{obj}" /> joka vaatii vähintään <skill skill="{skill}"/>tason
      <numberProgress current="{current}" max="{max}" />.
