singulars:
  traveling:
    text: Matkustaessa
  locationHasKeywords:
    text: Ollessasi paikassa <object id="{obj}" />.
  achievementPoints:
    text: Kerää <icon i="achievement point"/> <numberProgress current="{current}"
      max="{max}" /> saavutuspistettä.
  achievementPointsPercent:
    text: Kerää <icon i="achievement point"/><numberProgress current="{current}" max="{max}"
      /> saavutuspistettä ({percentage}% kokonaismäärästä).
  haveCoins:
    text: Kerää <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> rahaa.
  minimumSkillLevel:
    text: Saavuta jokaisessa taidossa vähintään taso <numberProgress current="{current}"
      max="{max}" />.
  levelUpSkills:
    text: Kehitä taitojesi tasoja <numberProgress current="{current}" max="{max}"
      /> kertaa.
  haveItemStack:
    text: Omista <object id="{obj}" alwaysShow="true" /> esineelle pino, jossa on
      esineitä vähintään <numberProgress current="{current}" max="{max}" />.
  exploreRegion:
    text: Tutki <object id="{obj}" alwaysShow="true" /> kokonaan. <numberProgress
      current="{current}" max="{max}" />.
  haveBankStacks:
    text: Pankissasi on <numberProgress current="{current}" max="{max}" /> esinepinoa
      tavaroita.
  activityType:
    singleKeyword: Tehdessäsi <object id="{obj}" /> aktiviteettia.
  service:
    text: Vaatii <serviceTier tier="{tier}" /> tason <object id="{obj}" /> palvelun
      tai paremman.
  realm:
    text: Ollessasi maassa <realm realm="{realm}" />.
  uniques:
    woodCarving: Suorita Puunveistoaktiviteetti <numberProgress current="{current}"
      max="{max} /> kertaa.
    intermediateShipRepair: Suorita Keskitatson laivankorjaus -aktiviteetti <numberProgress
      current="{current}" max="{max} /> kertaa.
    firewoodMaking: Suorita Polttopuiden teko -aktiviteetti <numberProgress current="{current}"
      max="{max} /> kertaa.
    intermediateCrossCountry: Suorita Keskitason maastohiihto -aktiviteetti <numberProgress
      current="{current}" max="{max} /> kertaa.
    beginnerCrossCountry: Suorita Aloittelijan maastohiihto -aktiviteetti <numberProgress
      current="{current}" max="{max} /> kertaa.
    searchTeam: Suorita Mustasilmähuipun etsintätiimi -aktiviteetti <numberProgress
      current="{current}" max="{max} /> kertaa.
  factionReputations:
    syrenthiaReputation: Saavuta mainetta <numberProgress current="{current}" max="{max}"
      /> verran ryhmittymään <realm realm="faction-syrenthia-6e9359fa-597b-4448-9df5-cc3fff9a5108"
      />.
    trellinReputation: Saavuta mainetta <numberProgress current="{current}" max="{max}"
      /> verran ryhmittymään <realm realm="faction-trellin-239a0ad8-3812-4f2a-9c11-1c312490249b"
      />.
    erdwiseReputation: Saavuta mainetta <numberProgress current="{current}" max="{max}"
      /> verran ryhmittymään <realm realm="faction-erdwise-697ae8a6-491e-46fd-8a05-4b744f9630eb"
      />.
    jarvoniaReputation: Saavuta mainetta <numberProgress current="{current}" max="{max}"
      /> verran ryhmittymään <realm realm="faction-jarvonia-1b061315-a63d-4dc1-a8ba-10902a83c5db"
      />.
  mainSkill:
    text: Kun suoritat taitoa <skill skill="{skill}"/>
  skillLevel:
    text: Vähintään <skill skill="{skill}" level="{level}" vaadittu/>
  itemAnywhereWithYou:
    text: Esine <item id="{item}"/> on mukanasi.
  itemEquipped:
    text: Esine <item id="{item}"/> on puettuna.
  itemInInventory:
    text: Esine <item id="{item}"/> on repussasi.
  itemAnywhere:
    text: Omista esine <item id="{item}"/>.
  distinctItemsEquippedKeyword:
    text: Pidä <numberProgress current="{current}" max="{max}" /> kappaletta esinettä
      <object id="{obj}" /> puettuna.
  totalSteps:
    text: Kävele yhteensä <numberProgress current="{current}" max="{max}" /> askelta.
  characterLevel:
    text: Saavuta hahmon taso <numberProgress current="{current}" max="{max}" />.
  unlocked:
    text: Olen avannut lukituksen <object id="{obj}" alwaysShow="true" />.
  overencumbered:
    text: Ylitä reppusi kantoraja.
