singulars:
  traveling:
    text: Mens du reiser.
  mainSkillType:
    text: Mens du gjør <skillType type="{type}"/> egenskaper.
  mainSkill:
    text: Mens du gjør <skill skill="{skill}"/>.
  itemAnywhereWithYou:
    text: Ha gjenstand <item id="{item}"/> med deg.
  itemEquipped:
    text: Ha gjenstand <item id="{item}"/> utstyrt.
