singulars:
  skillLevel:
    text: Almeno <skill skill="{skill}" level="{level}" needed/>
  itemAnywhereWithYou:
    text: Avere <item id="{item}"/> con te.
  mainSkill:
    text: Mentre si fa <skill skill="{skill}"/>
  traveling:
    text: Viaggiando
  itemEquipped:
    text: Avere <item id="{item}"/> equipaggiato.
  itemInInventory:
    text: Avere <item id="{item}"/> nell’inventario.
  itemAnywhere:
    text: Avere <item id="{item}"/>.
  totalSteps:
    text: Avere <numberProgress current="{current}" max="{max}" /> passi camminati
      in totale.
