singulars:
  skillLevel:
    text: Almeno <skill skill="{skill}" level="{level}" needed/>
  itemAnywhereWithYou:
    text: ''
  mainSkill:
    text: Mentre si fa <skill skill="{skill}"/>
  traveling:
    text: Viaggiando
  itemEquipped:
    text: ''
  itemInInventory:
    text: ''
  itemAnywhere:
    text: ''
  totalSteps:
    text: Avere <numberProgress current="{current}" max="{max}" /> passi camminati
      in totale.
  unlocked:
    text: Aver sbloccato <object id="{obj}" alwaysShow="true" />.
  exploreRealm:
    text: Esplora completamente <object id="{obj}" alwaysShow="true" />. <numberProgress
      current="{current}" max="{max}" />.
