singulars:
  skillLevel:
    text: Almeno <skill skill="{skill}" level="{level}" necessario/>.
  itemAnywhereWithYou:
    text: 'Hai con te l''articolo <item id="{item}"/>.'
  mainSkill:
    text: Mentre si fa <skill skill="{skill}"/>.
  traveling:
    text: Viaggiando.
  itemEquipped:
    text: 'Equipaggia l''oggetto <item id="{item}"/>.'
  itemInInventory:
    text: 'Hai l''oggetto <item id="{item}"/> nell'' inventario.'
  itemAnywhere:
    text: 'Hai l''oggetto <item id="{item}"/>.'
  totalSteps:
    text: Avere <numberProgress current="{current}" max="{max}" /> passi camminati
      in totale.
  unlocked:
    text: Aver sbloccato <object id="{obj}" alwaysShow="true" />.
  exploreRealm:
    text: Esplora completamente <object id="{obj}" alwaysShow="true" />. <numberProgress
      current="{current}" max="{max}" />.
  mainSkillType:
    text: Mentre si eseguono abilità <skillType type="{type}"/>.
  itemQualityEquipped:
    withoutType: Avere almeno <numberProgress current="{current}" max="{max}" /> oggetti
      <itemQuality quality="{quality}" type="crafted"/> o <itemQuality quality="{quality}"
      type="loot"/> equipaggiati.
    text: Avere almeno <numberProgress current="{current}" max="{max}" /> <itemQuality
      quality="{quality}" type="{type}"/> oggetti equipaggiati.
  keywordEquipped:
    text: Necessario equipaggiare <object id="{obj}" />.
  keywordWithLevelEquipped:
    text: Dotati di <object id="{obj}" /> che richiede almeno <skill skill="{skill}"/>
      livello <numberProgress current="{current}" max="{max}" />.
  distinctItemsEquippedKeyword:
    text: Richiede <numberProgress current="{current}" max="{max}" /> unico <object
      id="{obj}" /> equipaggiato.
  characterLevel:
    text: Avere livello personaggio <numberProgress current="{current}" max="{max}"
      />.
  achievementPoints:
    text: Avere <icon i="punto obiettivo"/> <numberProgress current="{current}" max="{max}"
      /> punti obiettivo.
  achievementPointsPercent:
    text: Avere <icon i="achievement point"/> <numberProgress current="{current}"
      max="{max}" /> punti obiettivo ({percentage}% del totale).
  haveCoins:
    text: Hai <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> monete.
  minimumSkillLevel:
    text: Avere ogni abilità almeno al livello <numberProgress current="{current}"
      max="{max}" />.
  levelUpSkills:
    text: Migliora le tue abilità <numberProgress current="{current}" max="{max}"
      /> volte.
  overencumbered:
    text: Il tuo inventario supera il limite (sovraccarico).
  haveItemStack:
    text: Avere una pila di elementi <object id="{obj}" alwaysShow="true" /> con dimensione
      <numberProgress current="{current}" max="{max}" />.
  haveBankStacks:
    text: Hai <numberProgress current="{current}" max="{max}" /> oggetti nella tua
      banca.
  activityType:
    singleKeyword: Durante l'esecuzione dell'attività <object id="{obj}" />.
  service:
    text: Necessario <serviceTier tier="{tier}" /> <object id="{obj}" /> o superiore.
  realm:
    text: Mentre ci si trova nell'area <realm realm="{realm}" />.
  uniques:
    intermediateCrossCountry: Completa l'attività <object 
      id="activity-cross-country_skiing_(intermediate)-42788047-6cc3-4711-88be-999e9504fc2a"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> volte.
    firewoodMaking: Completa l'attività <object id="activity-firewood_making-407263a4-4ee1-4383-a624-2a7ed70c4b10"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> volte.
    searchTeam: Completa l'attività del Picco dell'cchio Nero <object id="activity-black_eye_peak_search_team-d1ad835f-0898-4fc7-8f0a-4b0626d95306"
      alwaysShow="true" /> in <object id="location-horn_of_respite-1661d247-11f1-49eb
      -b927-6e59c8fd7774" alwaysShow="true" /> <numberProgress current="{current}"
      max="{max}" /> volte.
    intermediateShipRepair: Completa l'attività <object id="activity-ship_repair_(intermediate)-44f2f2e7-bef1-437f-ac35-bf64b97cc249"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> volte.
    beginnerCrossCountry: Completa l'attività <object 
      id="activity-cross-country_skiing_(beginner)-fc421940-d63a-402f-aa50-26cc2efea4d3"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> volte.
    woodCarving: Completa l'attività <object id="activity-wood_carving-af675674-c972-4e2e-80fe-1501b972e353"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> volte.
    wraithwaterBankRebuild: <object id="2808f754-9d31-4243-a711-7214a2a1c7b7" alwaysShow="true"
      />.
    wreckDiving: Completa l'attività <object id="activity-wreck_diving-12e980cd-058a-42c4-8358-ba7afe1c319c"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> volte.
  gear:
    swimmingExpert: Completata l'attività <object id="activity-swimming_(expert)-95a78afb-79f0-431c-b7aa-062659d9ec87"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> volte.
    tinkering: Aver completato l'attività <object id="activity-tinkering-cb2a8773-06d0-4661-9708-2bef5768119e"
      /> attività <numberProgress current="{current}" max="{max}" /> volte in <object
      id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a" alwaysShow="true"
      />
    beginnerSkydisc: Completata l'attività <object id="activity-frisbee_golfing_(beginner)-0fb41f4d-f46b-4a6d-acdf
      -f2525654c714" alwaysShow="true" /> attività in <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> volte.
    underwaterBasketweaving: Completata l'attività <object id="activity-underwater_basket_weaving-7ba725a2-d147-437c-98bf
      -5a9f58d68b65" alwaysShow="true" /> attività <numberProgress current="{current}"
      max="{max}" /> volte in <object id="location-fertile_shallows-6561e4b5-fce3-4307-a641-86ca5aee36d6"
      alwaysShow="true" />
    iceSculpting: Completata l'attività <object id="activity-ice_sculpting-2b0be0f5-69d5-4205-922d
      -c5a02c056cab" alwaysShow="true" /> attività  <numberProgress current="{current}"
      max="{max}" /> volte in <object id="location-frusenholm-5ddb0735-4582-4858-80a0-7489f1b043a2"
      alwaysShow="true" />
    sledding: Durante l'attività <object id="activity-sledding-290bfd6c-3bb1-47c6-bf60-880c1d4a5148"
      />.
  factionReputations:
    jarvoniaReputation: Avere <numberProgress current="{current}" max="{max}" /> <realm
      realm="faction-jarvonia-1b061315-a63d-4dc1-a8ba-10902a83c5db" /> reputazione
      di fazione.
    trellinReputation: Avere <numberProgress current="{current}" max="{max}" /> <realm
      realm="faction-trellin-239a0ad8-3812-4f2a-9c11-1c312490249b" /> reputazione
      di fazione.
    syrenthiaReputation: Avere <numberProgress current="{current}" max="{max}" />
      <realm realm="faction-syrenthia-6e9359fa-597b-4448-9df5-cc3fff9a5108" /> reputazione
      di fazione.
    erdwiseReputation: Avere <numberProgress current="{current}" max="{max}" /> <realm
      realm="faction-erdwise-697ae8a6-491e-46fd-8a05-4b744f9630eb" /> reputazione
      di fazione.
    halflingRebelsReputation: Avere <numberProgress current="{current}" max="{max}"
      /> <realm realm="faction-halfling_rebels-394eaff8-2749-4473-949c-80da531a415e"
      /> reputazione di fazione.
  maps:
    erdwiseMap: Possedere un <object id="fa277527-585b-4a1d-bc73-a25fe1195017" />.
    halflingMap: Possedere un <object id="f1a9e370-fd69-4a49-92c0-c83475a896ab" />.
    jarvoniaMap: Possedere un <object id="item-map_of_jarvonia-86ba96b3-a845-4f5c-a054-04ec5146fb25"
      />.
    syrenthiaMap: Possedere un <object id="65979ee2-f98a-41c3-9f12-8858000017a3" />.
    trellinMap: Possedere un <object id="item-map_of_gdte-b28951b2-2cac-4e53-b6f1-bc2030590433"
      />.
  locationHasKeywords:
    text: Mentre ci si trova in <object id="{obj}" />.
  serviceKeywords:
    text: Richiede <serviceTier tier="{tier}" /> {objects} servizio o superiore.
  petTotalLevels:
    text: Ottieni un totale di <numberProgress current="{current}" max="{max}" />
      livelli per tutti i tuoi animali domestici.
  petHighestLevel:
    text: Avere un animale domestico con almeno il livello <numberProgress current="{current}"
      max="{max}" />.
  itemsWithKeywordCrafted:
    text: Hai creato <object id="{obj}" /> oggetti. <numberProgress current="{current}"
      max="{max}" />.
  itemsGained:
    text: Guadagno <object id="{obj}" />. <numberProgress current="{current}" max="{max}"
      />.
  abilityAvailable:
    text: Avendo a disposizione la funzionalità <object id="{obj}" />.
  petWithKeyword:
    text: Avere <object id="{obj}" /> animali domestici. <numberProgress current="{current}"
      max="{max}" />.
    textDistinct: Possiedi animali domestici unici <object id="{obj}" />. <numberProgress
      current="{current}" max="{max}" />.
  hasPet:
    text: Avere un animale domestico <object id="{obj}" />.
  petAmount:
    text: Hai <numberProgress current="{current}" max="{max}" /> animali domestici.
  totalSkillLevel:
    text: Hai un livello di abilità totale pari a <numberProgress current="{current}"
      max="{max}" />.
