singulars:
  skillLevel:
    text: Almeno <skill skill="{skill}" level="{level}" needed/>
  itemAnywhereWithYou:
    text: 'Hai con te l''articolo <item id="{item}"/>.'
  mainSkill:
    text: Mentre si fa <skill skill="{skill}"/>
  traveling:
    text: Viaggiando
  itemEquipped:
    text: 'Equipaggia l''oggetto <item id="{item}"/>.'
  itemInInventory:
    text: 'Hai l''oggetto <item id="{item}"/> nell'' inventario.'
  itemAnywhere:
    text: 'Hai l''oggetto <item id="{item}"/>.'
  totalSteps:
    text: Avere <numberProgress current="{current}" max="{max}" /> passi camminati
      in totale.
  unlocked:
    text: Aver sbloccato <object id="{obj}" alwaysShow="true" />.
  exploreRealm:
    text: Esplora completamente <object id="{obj}" alwaysShow="true" />. <numberProgress
      current="{current}" max="{max}" />.
