singulars:
  smithing:
    basicForge:
      name: Базова кузня
      desc: Початкова кузня, ідеальна для виготовлення простих предметів.
    advancedForge:
      name: Просунута кузня
      desc: Більш досконала кузня, ідеальна для створення складних та високоякісних
        виробів.
    frozenForge:
      name: Заморожена кузня
      desc: Кузня, зроблена з льоду з маленькими різьбленнями пінгвінів по всій поверхні.
    underwaterForge:
      name: Підводна кузня (базова)
      desc: Підводна кузня працює від гарячих парових гейзерів, що забезпечують достатньо
        тепла для плавлення металу.
  trinketry:
    advancedTrinketryBench:
      desc: Скромний верстат, наповнений лінзами, наждачним папером та іншими інструментами
        досвідченого виробника прикрас.
      name: Просунутий ювелірний верстат
    erdwissTrinketryFactory:
      name: Ювелірна фабрика Ердвісс (просунута)
      desc: ЮФЕ має одні з найкращих машин, імпортованих з Гейлфорджа для огранки
        самоцвітів.
    basicTrinketryBench:
      name: Базовий ювелірний верстат
      desc: Робочий верстат, призначений для огранки самоцвітів та виготовлення простих
        прикрас.
    ruinedTrinketryBench:
      name: Зруйнований ювелірний верстат (базовий)
      desc: У руїнах Кінця Зими стоїть стародавній ювелірний верстат, покритий мохом
        та грибами.
  carpentry:
    basicSawmill:
      name: Базова лісопилка
      desc: Елементарне підприємство з обробки деревини, де колоди перетворюються
        на базові пиломатеріали.
    advancedSawmill:
      name: Просунута лісопилка
      desc: Просунута лісопилка, здатна виробляти високоякісні пиломатеріали з точністю
        та ефективністю.
    barbantokSawmill:
      name: Лісопилка Барбантока (базова)
      desc: Лісопилка, яка, як кажуть, населена привидом Барбантока, легендарного
        столяра, відомого своєю винятковою майстерністю.
    underwaterSawmill:
      name: Підводна лісопилка (базова)
      desc: Лісопилка, ідеальна для роботи з деревоподібними коралами, але також забезпечує
        інструменти для перетворення будь-яких колод на дошки.
    sawInHalfMill:
      name: Лісопилка "Розпил навпіл" (просунута)
      desc: Лісопилка хафлінгів - це диво інженерії, що покладається на потік води
        через підводний акведук та витончене водяне колесо.
  tailoring:
    advancedLoom:
      name: Просунутий ткацький верстат
      desc: Добре обладнана майстерня з найсучаснішим ткацьким верстатом та елегантним
        швейним столом, наповнена ретельно підібраним асортиментом преміальних тканин
        та спеціалізованих інструментів, ідеальна для досвідчених кравців, які прагнуть
        створювати вишукані вбрання.
    basicLoom:
      name: Базовий ткацький верстат
      desc: Скромна майстерня з міцним ткацьким верстатом та потертим швейним столом,
        наповнена асортиментом тканин та інструментів, ідеальна для початківців кравців,
        які прагнуть вивчити мистецтво пошиття одягу.
  cosmetics:
    barber:
      name: Перукар
      desc: Перукар, який може змінити вашу зачіску на іншу.
    wardrobe:
      name: Гардероб
      desc: Доступ до вашого гардеробу, щоб ви могли змінити свій вигляд на будь-які
        косметичні предмети, які у вас є.
  cooking:
    basicKitchen:
      name: Базова кухня
      desc: Скромне кухонне обладнання, де ви можете готувати прості та корисні страви.
    advancedKitchen:
      name: Просунута кухня
      desc: Добре обладнана кухня, підходяща для гурманської кулінарії та кулінарних
        експериментів.
    underwaterKitchen:
      name: Підводна кухня (базова)
      desc: Ця кухня обладнана різними кулінарними інструментами, пристосованими для
        приготування їжі під водою.
    eberhartMansionKitchen:
      name: Кухня маєтку Ебергарт (просунута)
      desc: Родина Ебергарт дає тим, хто дає іншим. Доказ вашої відданості місцевій
        безкоштовній їдальні - це більш ніж достатня причина для них відкрити свої
        двері та дозволити вам користуватися їхнім спільним кухонним простором.
  crafting:
    basicWorkshop:
      name: Базова майстерня
      desc: Базове обладнання майстерні, призначене для виготовлення простих та практичних
        предметів.
    advancedWorkshop:
      name: Просунута майстерня
      desc: Просунута майстерня, обладнана для створення складних та універсальних
        виробів.
    tidalWorkshop:
      name: Припливна майстерня (просунута)
      desc: Майстерня, на яку завжди впливає течія. Вона має всі інструменти, необхідні
        для виготовлення речей.
maps:
  tiers:
    "basic": Базовий
    "advanced": Просунутий
    "legendary": Легендарний
    "mythic": Міфічний
