singulars:
  mainSkill:
    text: Ao fazer <skill skill="{skill}"/>
  skillLevel:
    text: Necessário pelo menos <nível skill="{skill}" level="{level}"/>
  traveling:
    text: Enquanto viaja
  itemAnywhereWithYou:
    text: Tenha o item <item id="{item}"/> com você.
  itemEquipped:
    text: Tenha o item <item id="{item}"/> equipado.
  totalSteps:
    text: Tenha <numberProgress current="{current}" max="{max}" /> passos dados no
      total.
  characterLevel:
    text: Tenha o nível <numberProgress current="{current}" max="{max}" /> do personagem.
  unlocked:
    text: Ter desbloqueado <object id="{obj}" alwaysShow="true" />.
  achievementPointsPercent:
    text: Tenha <icon i="achievement point"/> <numberProgress current="{current}"
      max="{max}" /> pontos de conquista ({percentage}% do total).
  itemInInventory:
    text: Tenha o item <item id="{item}"/> no seu inventário.
  itemAnywhere:
    text: Tenha o item <item id="{item}"/>.
  distinctItemsEquippedKeyword:
    text: Tenha <numberProgress current="{current}" max="{max}" /> de <object id="{obj}"
      /> equipado.
  achievementPoints:
    text: Tenha <icon i="achievement point"/> <numberProgress current="{current}"
      max="{max}" /> pontos de conquista.
