singulars:
  cooking:
    basicKitchen:
      name: Cozinha Básica
    advancedKitchen:
      name: Cozinha Avançada
  smithing:
    basicForge:
      name: Forja Básica
    advancedForge:
      name: Forja Avançada
    frozenForge:
      name: Forja Congelada
