singulars:
  mainSkillType:
    text: 當進行<skillType type="{type}"/>技能。
  traveling:
    text: 當旅行時。
  itemAnywhereWithYou:
    text: 攜帶物品<item id="{item}"/>。
  itemEquipped:
    text: 裝備物品<item id="{item}"/>。
  itemInInventory:
    text: 攜帶物品<item id="{item}"/>於背包內。
  itemAnywhere:
    text: 擁有物品<item id="{item}"/>。
  itemQualityEquipped:
    text: 裝備至少<numberProgress current="{current}" max="{max}" /><itemQuality quality="{quality}"
      type="{type}"/>。
    withoutType: 裝備至少<numberProgress current="{current}" max="{max}" /><itemQuality
      quality="{quality}" type="crafted"/>或<itemQuality quality="{quality}" type="loot"/>。
  mainSkill:
    text: 當進行<skill skill="{skill}"/>。
  keywordEquipped:
    text: 裝備着<object id="{obj}" />。
  distinctItemsEquippedKeyword:
    text: 需要裝備<numberProgress current="{current}" max="{max}" /><object id="{obj}"
      />。
  distinctKeywordItemInInventory:
    text: 背包需要擁有<numberProgress current="{current}" max="{max}" /><object id="{obj}"
      />。
  totalSteps:
    text: 需要步行<numberProgress current="{current}" max="{max}" />步。
  characterLevel:
    text: 角色等級需達<numberProgress current="{current}" max="{max}" />級。
  unlocked:
    text: 需已解鎖<object id="{obj}" alwaysShow="true" />。
  achievementPoints:
    text: 需要有<icon i="achievement point"/><numberProgress current="{current}" max="{max}"
      />成就點數。
  haveCoins:
    text: 需持有<icon i="money small"/><numberProgress current="{current}" max="{max}"
      />金幣。
  minimumSkillLevel:
    text: 每種技能需至少<numberProgress current="{current}" max="{max}" />級。
  levelUpSkills:
    text: 提升技能<numberProgress current="{current}" max="{max}" />次。
  activityType:
    singleKeyword: 當進行<object id="{obj}" />時。
  recipeType:
    text: 當進行<object id="{obj}" />食譜。
  service:
    text: 需要<serviceTier tier="{tier}" /><object id="{obj}" />或更好的服務。
  currentService:
    text: 需要<serviceTier tier="{tier}" /><object id="{obj}" />或更好的服務。你未能使用<object
      id="{currentObj}" icon="false" />。
  realm:
    text: 在<realm realm="{realm}" />地區時。
  locationHasKeywords:
    text: 在<object id="{obj}" />地方時。
  petWithKeyword:
    text: 擁有<object id="{obj}" />寵物。<numberProgress current="{current}" max="{max}"
      />。
  hasPet:
    text: 擁有一隻寵物<object id="{obj}" />。
  petAmount:
    text: 擁有<numberProgress current="{current}" max="{max}" />寵物。
  petHighestLevel:
    text: 需擁有一隻最少<numberProgress current="{current}" max="{max}" />級的寵物。
  itemsGained:
    text: 獲得<object id="{obj}" />。<numberProgress current="{current}" max="{max}"
      />。
  petsHatched:
    text: 擁有任何<object id="pet_egg" /><numberProgress current="{current}" max="{max}"
      />。
  achievementPointsPercent:
    text: 擁有<icon i="achievement point"/><numberProgress current="{current}" max="{max}"
      />成就點數（總數的{percentage}%）。
  uniques:
    beginnerCrossCountry: 完成<numberProgress current="{current}" max="{max}" />次<object
      id="activity-cross-country_skiing_(beginner)-fc421940-d63a-402f-aa50-26cc2efea4d3"
      alwaysShow="true" />活動。
    firewoodMaking: 完成<numberProgress current="{current}" max="{max}" />次<object id="activity-firewood_making-407263a4-4ee1-4383-a624-2a7ed70c4b10"
      alwaysShow="true" />。
    intermediateCrossCountry: 完成<numberProgress current="{current}" max="{max}" />次<object
      id="activity-cross-country_skiing_(intermediate)-42788047-6cc3-4711-88be-999e9504fc2a"
      alwaysShow="true" />。
    woodCarving: 完成<numberProgress current="{current}" max="{max}" />次<object id="activity-wood_carving-af675674-c972-4e2e-80fe-1501b972e353"
      alwaysShow="true" />。
  collectiblesOwned:
    text: 獲得<icon i="Collectible" />收藏品<numberProgress current="{current}" max="{max}"
      />。
  skillLevel:
    text: 至少<skill skill="{skill}" level="{level}" needed/>。
