singulars:
  mainSkill:
    text: Al hacer <skill skill="{skill}"/>
  skillLevel:
    text: Al menos <skill skill="{skill}" level="{level}"" needed/>
  traveling:
    text: Al viajar
  itemAnywhereWithYou:
    text: Ten el objeto <item id="{item}"/>.
  itemEquipped:
    text: Tener equipado el objeto <item id="{item}"/>.
  itemInInventory:
    text: Ten el objeto <item id="{item}"/> en tu inventario.
  itemAnywhere:
    text: Ten el objeto <item id="{item}"/>.
  distinctItemsEquippedKeyword:
    text: Ten<numberProgress current="{current}" max="{max}" /> de <object id="{obj}"
      /> equipado.
  totalSteps:
    text: Ten <numberProgress current="{current}" max="{max}" /> pasos caminados en
      total.
  characterLevel:
    text: Ten nivel de personaje <numberProgress current="{current}" max="{max}" />.
  unlocked:
    text: Has desbloqueado <object id="{obj}" alwaysShow="true" />.
  achievementPointsPercent:
    text: Ten <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> puntos de logro ({porcentaje}% del total).
  haveCoins:
    text: Ten <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> monedas.
  levelUpSkills:
    text: Sube de nivel tus habilidades <numberProgress current="{current}" max="{max}"
      /> veces.
  overencumbered:
    text: Ten tu inventario por encima del límite (sobrecarga).
  minimumSkillLevel:
    text: Ten todas las habilidades al menos al nivel <numberProgress current="{current}"
      max="{max}" />.
  achievementPoints:
    text: Ten<icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> puntos de logro.
  haveItemStack:
    text: Ten una pila de objetos de <object id="{obj}" alwaysShow="true" /> con el
      tamaño de <numberProgress current="{current}" max="{max}" />.
  service:
    text: Necesita un servicio de <serviceTier tier="{tier}" /> <object id="{obj}"
      /> o mejor.
  exploreRegion:
    text: Explora<object id="{obj}" alwaysShow="true" /> por completo. <numberProgress
      current="{current}" max="{max}" />.
  haveBankStacks:
    text: Ten <numberProgress current="{current}" max="{max}" /> pilas de objetos
      en tu banco.
  activityType:
    singleKeyword: Mientras se realiza la actividad <object id="{obj}" />.
  realm:
    text: Mientras estés en <realm realm="{realm}" />.
  locationHasKeywords:
    text: Mientras estés en ubicación <object id="{obj}" />.
