singulars:
  mainSkill:
    text: Tijdens het trainen van <skill skill="{skill}"/>.
  skillLevel:
    text: Minstens <skill skill="{skill}" level="{level}" vereist/>.
  traveling:
    text: Tijdens het reizen.
  itemAnywhereWithYou:
    text: Heb voorwerp <item id="{item}"/> bij je.
  itemEquipped:
    text: Draag voorwerp <item id="{item}"/>.
  itemInInventory:
    text: Heb voorwerp <item id="{item}"/> in je inventaris.
  itemAnywhere:
    text: Heb voorwerp <item id="{item}"/>.
  distinctItemsEquippedKeyword:
    text: Vereist het dragen van <numberProgress current="{current}" max="{max}" />
      verschillende <object id="{obj}" />.
  totalSteps:
    text: Heb in totaal <numberProgress current="{current}" max="{max}" /> stappen
      genomen.
  characterLevel:
    text: Heb personageniveau <numberProgress current="{current}" max="{max}" />.
  unlocked:
    text: Heb <object id="{obj}" alwaysShow="true" /> ontgrendeld.
  achievementPoints:
    text: Heb <icon i="achievement point"/><numberProgress current="{current}" max="{max}"
      /> prestatiepunten.
  achievementPointsPercent:
    text: Heb <icon i="achievement point"/><numberProgress current="{current}" max="{max}"
      /> prestatiepunten ({percentage} van het totaal).
  haveCoins:
    text: Heb <icon i="money small"/><numberProgress current="{current}" max="{max}"
      /> munten.
  minimumSkillLevel:
    text: Heb minstens niveau <numberProgress current="{current}" max="{max}" /> in
      elke vaardigheid.
  levelUpSkills:
    text: Ga <numberProgress current="{current}" max="{max}" /> keer een niveau omhoog.
  overencumbered:
    text: Heb meer in je inventaris dan het limiet (overbelast).
  haveItemStack:
    text: Heb een stapel <object id="{obj}" alwaysShow="true" /> voorwerpen met een
      grootte van <numberProgress current="{current}" max="{max}" />.
  exploreRegion:
    text: Verken <object id="{obj}" alwaysShow="true" /> volledig. <numberProgress
      current="{current}" max="{max}" />.
  haveBankStacks:
    text: Heb <numberProgress current="{current}" max="{max}" /> stapels aan voorwerpen
      in je bank.
  activityType:
    singleKeyword: Bij het uitvoeren van de <object id="{obj}" /> activiteit.
  service:
    text: Vereist <serviceTier tier="{tier}" /><object id="{obj}" /> voorziening of
      beter.
  realm:
    text: Terwijl je je in de <realm realm="{realm}" /> omgeving bevindt.
  locationHasKeywords:
    text: Terwijl je op locatie <object id="{obj}" /> bent.
  uniques:
    beginnerCrossCountry: Voltooi de <object 
      id="activity-cross-country_skiing_(beginner)-fc421940-d63a-402f-aa50-26cc2efea4d3"
      alwaysShow="true" /> activiteit <numberProgress current="{current}" max="{max}"
      /> keer.
    intermediateCrossCountry: Voltooi de <object 
      id="activity-cross-country_skiing_(intermediate)-42788047-6cc3-4711-88be-999e9504fc2a"
      alwaysShow="true" /> activiteit <numberProgress current="{current}" max="{max}"
      /> keer.
    firewoodMaking: Voltooi de <object id="activity-firewood_making-407263a4-4ee1-4383-a624-2a7ed70c4b10"
      alwaysShow="true" /> activiteit <numberProgress current="{current}" max="{max}"
      /> keer.
    woodCarving: Voltooi de <object id="activity-wood_carving-af675674-c972-4e2e-80fe-1501b972e353"
      alwaysShow="true" /> activiteit <numberProgress current="{current}" max="{max}"
      /> keer.
    searchTeam: Voltooi de Zwartoogpiek <object id="activity-black_eye_peak_search_team-d1ad835f-0898-4fc7-8f0a-4b0626d95306"
      alwaysShow="true" /> actitiveit in <object id="location-horn_of_respite-1661d247-11f1-49eb-b927-6e59c8fd7774"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> keer.
    intermediateShipRepair: Voltooi de <object id="activity-ship_repair_(intermediate)-44f2f2e7-bef1-437f-ac35-bf64b97cc249"
      alwaysShow="true" /> activiteit <numberProgress current="{current}" max="{max}"
      /> keer.
    wraithwaterBankRebuild: <object id="2808f754-9d31-4243-a711-7214a2a1c7b7" alwaysShow="true"
      />.
    notUnderwater: Niet op een <object id="location_underwater" /> locatie.
    notAgility: Niet <skill skill="agility"/> doen.
    smeltRecipe: Bij het uitvoeren van <object id="recipe_smelting" /> recepten.
    wreckDiving: Voltooi <numberProgress current="{current}" max="{max}" /> keer de
      <object id="activity-wreck_diving-12e980cd-058a-42c4-8358-ba7afe1c319c" alwaysShow="true"
      /> activiteit.
  factionReputations:
    trellinReputation: Heb een factiereputatie van <numberProgress current="{current}"
      max="{max}" /> voor <realm realm="faction-trellin-239a0ad8-3812-4f2a-9c11-1c312490249b"
      />.
    jarvoniaReputation: Heb een factiereputatie van <numberProgress current="{current}"
      max="{max}" /> voor <realm realm="faction-jarvonia-1b061315-a63d-4dc1-a8ba-10902a83c5db"
      />.
    syrenthiaReputation: Heb een factiereputatie van <numberProgress current="{current}"
      max="{max}" /> voor <realm realm="faction-syrenthia-6e9359fa-597b-4448-9df5-cc3fff9a5108"
      />.
    erdwiseReputation: Heb een factiereputatie van <numberProgress current="{current}"
      max="{max}" /> voor <realm realm="faction-erdwise-697ae8a6-491e-46fd-8a05-4b744f9630eb"
      />.
    halflingRebelsReputation: Heb een factiereputatie van <numberProgress current="{current}"
      max="{max}" /> voor <realm realm="faction-halfling_rebels-394eaff8-2749-4473-949c-80da531a415e"
      />.
  exploreRealm:
    text: Verken <object id="{obj}" alwaysShow="true" /> volledig. <numberProgress
      current="{current}" max="{max}" />.
  gear:
    swimmingExpert: Voltooi de <object id="activity-swimming_(expert)-95a78afb-79f0-431c-b7aa-062659d9ec87"
      alwaysShow="true" /> activiteit <numberProgress current="{current}" max="{max}"
      /> keer.
    tinkering: Neem <numberProgress current="{current}" max="{max}" /> stappen tijdens
      de <object id="activity-tinkering-cb2a8773-06d0-4661-9708-2bef5768119e" /> activiteit
      in <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a" alwaysShow="true"
      />
    underwaterBasketweaving: Neem <numberProgress current="{current}" max="{max}"
      /> stappen tijdens de <object id="activity-underwater_basket_weaving-7ba725a2-d147-437c-98bf-5a9f58d68b65"
      alwaysShow="true" /> activiteit in <object id="location-fertile_shallows-6561e4b5-fce3-4307-a641-86ca5aee36d6"
      alwaysShow="true" />
    iceSculpting: Neem <numberProgress current="{current}" max="{max}" /> stappen
      tijdens de <object id="activity-ice_sculpting-2b0be0f5-69d5-4205-922d-c5a02c056cab"
      alwaysShow="true" /> activiteit in <object id="location-frusenholm-5ddb0735-4582-4858-80a0-7489f1b043a2"
      alwaysShow="true" />
    beginnerSkydisc: Voltooi de <object id="activity-frisbee_golfing_(beginner)-0fb41f4d-f46b-4a6d-acdf-f2525654c714"
      alwaysShow="true" /> activiteit in <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> keer.
    sledding: Tijdens de <object id="activity-sledding-290bfd6c-3bb1-47c6-bf60-880c1d4a5148"
      /> activiteit.
  maps:
    jarvoniaMap: Bezit een <object id="item-map_of_jarvonia-86ba96b3-a845-4f5c-a054-04ec5146fb25"
      />.
    syrenthiaMap: Bezit een <object id="65979ee2-f98a-41c3-9f12-8858000017a3" />.
    trellinMap: Bezit een <object id="item-map_of_gdte-b28951b2-2cac-4e53-b6f1-bc2030590433"
      />.
    erdwiseMap: Bezit een <object id="fa277527-585b-4a1d-bc73-a25fe1195017" />.
    halflingMap: Bezit een <object id="f1a9e370-fd69-4a49-92c0-c83475a896ab" />.
  mainSkillType:
    text: Tijdens het doen van <skillType type="{type}"/> vaardigheden.
  itemQualityEquipped:
    text: Draag minstens <numberProgress current="{current}" max="{max}" /><itemQuality
      quality="{quality}" type="{type}"/> voorwerpen.
    withoutType: Draag minstens <numberProgress current="{current}" max="{max}" /><itemQuality
      quality="{quality}" type="crafted"/> of <itemQuality quality="{quality}" type="loot"/>
      voorwerpen.
  keywordEquipped:
    text: Draag <object id="{obj}" />.
  keywordWithLevelEquipped:
    text: Draag <object id="{obj}" /> die minstens <skill skill="{skill}"/> niveau
      <numberProgress current="{current}" max="{max}" /> vereist.
  totalSkillLevel:
    text: Heb een totaal vaardigheidsniveau van <numberProgress current="{current}"
      max="{max}" />.
  serviceKeywords:
    text: Vereist <serviceTier tier="{tier}" /> {objects}-voorziening of beter.
  currentService:
    text: Je hebt een <serviceTier tier="{tier}" /><object id="{obj}" />-voorziening
      of beter nodig. Je kunt <object id="{currentObj}" icon="false" /> niet gebruiken.
  currentServiceKeywords:
    text: Je hebt een <serviceTier tier="{tier}" /> {objects}-voorziening of beter
      nodig. Je kunt <object id="{currentObj}" icon="false" /> niet gebruiken.
  recipeType:
    text: Bij het uitvoeren van <object id="{obj}" /> recepten.
  abilityAvailable:
    text: Als je de <object id="{obj}" /> ability beschikbaar hebt.
  petWithKeyword:
    text: Bezit <object id="{obj}" /> beestjes. <numberProgress current="{current}"
      max="{max}" />.
    textDistinct: Bezit <object id="{obj}" /> unieke beestjes. <numberProgress current="{current}"
      max="{max}" />.
  hasPet:
    text: Bezit een <object id="{obj}" /> beestje.
  petAmount:
    text: Bezit <numberProgress current="{current}" max="{max}" /> beestjes.
  petTotalLevels:
    text: Bereik een totaal niveau van <numberProgress current="{current}" max="{max}"
      /> verspreid over al je beestjes.
  petHighestLevel:
    text: Bezit een beestje met een niveau van minstens <numberProgress current="{current}"
      max="{max}" />.
  itemsWithKeywordCrafted:
    text: Bezit <object id="{obj}" /> handgemaakte voorwerpen. <numberProgress current="{current}"
      max="{max}" />.
  itemsGained:
    text: Verkrijg <object id="{obj}" />. <numberProgress current="{current}" max="{max}"
      />.
