singulars:
  mainSkill:
    text: Tijdens het trainen van <skill skill="{skill}"/>
  skillLevel:
    text: Tenminste <skill skill="{skill}" level="{level}" needed/>
  traveling:
    text: Tijdens het reizen
  itemAnywhereWithYou:
    text: Heb voorwerp <item id="{item}"/> bij je.
  itemEquipped:
    text: Draag voorwerp <item id="{item}"/>.
  itemInInventory:
    text: Heb voorwerp <item id="{item}"/> in je inventaris.
  itemAnywhere:
    text: Heb voorwerp <item id="{item}"/>.
  distinctItemsEquippedKeyword:
    text: Draag <numberProgress current="{current}" max="{max}" /> <object id="{obj}"
      />.
  totalSteps:
    text: Heb in totaal <numberProgress current="{current}" max="{max}" /> stappen
      genomen.
  characterLevel:
    text: Heb personageniveau <numberProgress current="{current}" max="{max}" />.
  unlocked:
    text: Heb <object id="{obj}" alwaysShow="true" /> ontgrendeld.
  achievementPoints:
    text: Heb <icon i="achievement point"/><numberProgress current="{current}" max="{max}"
      /> prestatiepunten.
  achievementPointsPercent:
    text: Heb <icon i="achievement point"/><numberProgress current="{current}" max="{max}"
      /> prestatiepunten ({percentage} van het totaal).
  haveCoins:
    text: Heb <icon i="money small"/><numberProgress current="{current}" max="{max}"
      /> munten.
  minimumSkillLevel:
    text: Heb minstens niveau <numberProgress current="{current}" max="{max}" /> in
      elke vaardigheid.
  levelUpSkills:
    text: Ga <numberProgress current="{current}" max="{max}" /> keer een niveau omhoog
      in je vaardigheden.
  overencumbered:
    text: Heb meer in je inventaris dan het limiet (overbelast).
  haveItemStack:
    text: Heb een stapel <object id="{obj}" alwaysShow="true" /> voorwerpen met een
      grootte van <numberProgress current="{current}" max="{max}" />.
  exploreRegion:
    text: Verken <object id="{obj}" alwaysShow="true" /> volledig. <numberProgress
      current="{current}" max="{max}" />.
  haveBankStacks:
    text: Heb <numberProgress current="{current}" max="{max}" /> stapels aan voorwerpen
      in je bank.
  activityType:
    singleKeyword: Bij het uitvoeren van de <object id="{obj}" /> activiteit.
  service:
    text: Vereist <serviceTier tier="{tier}" /><object id="{obj}" /> voorziening of
      beter.
  realm:
    text: Terwijl je in <realm realm="{realm}" /> bent.
  locationHasKeywords:
    text: Terwijl je op locatie <object id="{obj}" /> bent.
  uniques:
    beginnerCrossCountry: Voltooi de Beginners Langlaufen activiteit <numberProgress
      current="{current}" max="{max} /> keer.
    intermediateCrossCountry: Voltooi de Langlaufen Voor Gevorderden activiteit <numberProgress
      current="{current}" max="{max} /> keer.
    firewoodMaking: Voltooi de Brandhout Maken activiteit <numberProgress current="{current}"
      max="{max} /> keer.
    woodCarving: Voltooi de Houtkerven activiteit <numberProgress current="{current}"
      max="{max} /> keer.
