singulars:
  mainSkill:
    text: Tijdens het trainen van <skill skill="{skill}"/>
  skillLevel:
    text: Tenminste <skill skill="{skill}" level="{level}" benodigd/>
  traveling:
    text: Tijdens het reizen
  itemAnywhereWithYou:
    text: Heb voorwerp <item id="{item}"/> bij je.
  itemEquipped:
    text: Draag voorwerp <item id="{item}"/>.
  itemInInventory:
    text: Heb voorwerp <item id="{item}"/> in je inventaris.
