singulars:
  mainSkill:
    text: Tijdens het trainen van <skill skill="{skill}"/>
  skillLevel:
    text: Tenminste <skill skill="{skill}" level="{level}" benodigd/>
  traveling:
    text: Tijdens het reizen
