singulars:
  haveCoins:
    text: Avoir <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> pièces.
  mainSkill:
    text: En pratiquant la compétence <skill skill="{skill}"/>
  itemInInventory:
    text: Avoir <item id="{item}"/> dans votre inventaire.
  skillLevel:
    text: Au moins <skill skill="{skill}" level="{level}" needed/>
  traveling:
    text: En voyageant
  itemAnywhereWithYou:
    text: Avoir <item id="{item}"/> avec vous.
  itemAnywhere:
    text: Avoir <item id="{item}"/>.
  totalSteps:
    text: Avoir fait <numberProgress current="{current}" max="{max}" /> pas au total.
  characterLevel:
    text: Atteindre le niveau de personnage <numberProgress current="{current}" max="{max}"
      />.
  unlocked:
    text: Avoir débloqué <object id="{obj}" alwaysShow="true" />.
  service:
    text: Requiert <object id="{obj}" /> <serviceTier tier="{tier}" /> ou mieux.
