singulars:
  haveCoins:
    text: Avoir <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> pièces.
  mainSkill:
    text: En pratiquant la compétence <skill skill="{skill}"/>
