singulars:
  haveCoins:
    text: Avoir <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> pièces.
  mainSkill:
    text: En pratiquant la compétence <skill skill="{skill}"/>
  itemInInventory:
    text: Avoir <item id="{item}"/> dans votre inventaire.
  skillLevel:
    text: Au moins <skill skill="{skill}" level="{level}" needed/>
  traveling:
    text: En voyageant
  itemAnywhereWithYou:
    text: Avoir <item id="{item}"/> avec vous.
  itemAnywhere:
    text: Avoir <item id="{item}"/>.
  totalSteps:
    text: Avoir fait <numberProgress current="{current}" max="{max}" /> pas au total.
  characterLevel:
    text: Atteindre le niveau de personnage <numberProgress current="{current}" max="{max}"
      />.
  unlocked:
    text: Avoir débloqué <object id="{obj}" alwaysShow="true" />.
  service:
    text: Requiert <object id="{obj}" /> <serviceTier tier="{tier}" /> ou mieux.
  itemEquipped:
    text: Avoir équipé <item id="{item}"/>.
  distinctItemsEquippedKeyword:
    text: Avoir équipé <numberProgress current="{current}" max="{max}" /> <object
      id="{obj}" />.
  achievementPoints:
    text: Avoir <icon i="achievement point"/> <numberProgress current="{current}"
      max="{max}" /> points de succès.
  achievementPointsPercent:
    text: Avoir <icon i="achievement point"/> <numberProgress current="{current}"
      max="{max}" /> points de succès ({percentage}% du total).
  minimumSkillLevel:
    text: Avoir toutes les compétences au moins au niveau <numberProgress current="{current}"
      max="{max}" />.
  levelUpSkills:
    text: Monter les niveaux de vos compétences <numberProgress current="{current}"
      max="{max}" /> fois.
  overencumbered:
    text: Avoir dépassé la limite de votre inventaire (surchargé).
  exploreRealm:
    text: Explorer <object id="{obj}" alwaysShow="true" /> complètement. <numberProgress
      current="{current}" max="{max}" />.
  haveItemStack:
    text: Avoir une pile de <numberProgress current="{current}" max="{max}" /> <object
      id="{obj}" alwaysShow="true" />.
  haveBankStacks:
    text: Avoir <numberProgress current="{current}" max="{max}" /> piles d'objets
      en banque.
  activityType:
    singleKeyword: En effectuant <object id="{obj}" />.
  realm:
    text: Sur le territoire de <realm realm="{realm}" />.
  locationHasKeywords:
    text: Sur le lieu <object id="{obj}" />.
