singulars:
  haveCoins:
    text: Avoir <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> pièces.
  mainSkill:
    text: En pratiquant la compétence <skill skill="{skill}"/>
  itemInInventory:
    text: Avoir <item id="{item}"/> dans votre inventaire.
  skillLevel:
    text: Au moins <skill skill="{skill}" level="{level}" needed/>
  traveling:
    text: En voyageant
  itemAnywhereWithYou:
    text: Avoir <item id="{item}"/> avec vous.
  itemAnywhere:
    text: Avoir <item id="{item}"/>.
  totalSteps:
    text: Avoir fait <numberProgress current="{current}" max="{max}" /> pas au total.
  characterLevel:
    text: Atteindre le niveau de personnage <numberProgress current="{current}" max="{max}"
      />.
  unlocked:
    text: Avoir débloqué <object id="{obj}" alwaysShow="true" />.
  service:
    text: Requiert <object id="{obj}" /><serviceTier tier="{tier}" /> ou mieux.
  itemEquipped:
    text: Avoir équipé <item id="{item}"/>.
  distinctItemsEquippedKeyword:
    text: Avoir équipé <numberProgress current="{current}" max="{max}" /> <object
      id="{obj}" />.
  achievementPoints:
    text: Avoir <icon i="achievement point"/> <numberProgress current="{current}"
      max="{max}" /> points de succès.
  achievementPointsPercent:
    text: Avoir <icon i="achievement point"/> <numberProgress current="{current}"
      max="{max}" /> points de succès ({percentage}% du total).
  minimumSkillLevel:
    text: Avoir toutes les compétences au moins au niveau <numberProgress current="{current}"
      max="{max}" />.
  levelUpSkills:
    text: Monter les niveaux de vos compétences <numberProgress current="{current}"
      max="{max}" /> fois.
  overencumbered:
    text: Avoir dépassé la limite de votre inventaire (surchargé).
  exploreRealm:
    text: Explorer <object id="{obj}" alwaysShow="true" /> complètement. <numberProgress
      current="{current}" max="{max}" />.
  haveItemStack:
    text: Avoir une pile de <numberProgress current="{current}" max="{max}" /> <object
      id="{obj}" alwaysShow="true" />.
  haveBankStacks:
    text: Avoir <numberProgress current="{current}" max="{max}" /> piles d'objets
      en banque.
  activityType:
    singleKeyword: En effectuant <object id="{obj}" />.
  realm:
    text: Dans la zone de <realm realm="{realm}" />.
  locationHasKeywords:
    text: Sur le lieu <object id="{obj}" />.
  uniques:
    woodCarving: Terminer l'activité <object id="activity-wood_carving-af675674-c972-4e2e-80fe-1501b972e353"
      alwaysShow="true" /><numberProgress current="{current}" max="{max}" /> fois.
    beginnerCrossCountry: Terminer l'activité <object 
      id="activity-cross-country_skiing_(beginner)-fc421940-d63a-402f-aa50-26cc2efea4d3"
      alwaysShow="true" /><numberProgress current="{current}" max="{max}" /> fois.
    searchTeam: Terminer l'activité <object id="activity-black_eye_peak_search_team-d1ad835f-0898-4fc7-8f0a-4b0626d95306"
      alwaysShow="true" /> à <object id="location-horn_of_respite-1661d247-11f1-49eb-b927-6e59c8fd7774"
      alwaysShow="true" /><numberProgress current="{current}" max="{max}" /> fois.
    intermediateCrossCountry: Terminer l'activité <object 
      id="activity-cross-country_skiing_(intermediate)-42788047-6cc3-4711-88be-999e9504fc2a"
      alwaysShow="true" /><numberProgress current="{current}" max="{max}" /> fois.
    firewoodMaking: Terminer l'activité <object id="activity-firewood_making-407263a4-4ee1-4383-a624-2a7ed70c4b10"
      alwaysShow="true" /><numberProgress current="{current}" max="{max}" /> fois.
    intermediateShipRepair: Terminer l'activité <object id="activity-ship_repair_(intermediate)-44f2f2e7-bef1-437f-ac35-bf64b97cc249"
      alwaysShow="true" /><numberProgress current="{current}" max="{max}" /> fois.
  gear:
    tinkering: Marcher <numberProgress current="{current}" max="{max}" /> pas en faisant
      l'activité <object id="activity-tinkering-cb2a8773-06d0-4661-9708-2bef5768119e"
      /> à <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a" alwaysShow="true"
      />.
    iceSculpting: Marcher <numberProgress current="{current}" max="{max}" /> pas en
      faisant l'activité <object id="activity-ice_sculpting-2b0be0f5-69d5-4205-922d-c5a02c056cab"
      alwaysShow="true" /> à <object id="location-frusenholm-5ddb0735-4582-4858-80a0-7489f1b043a2"
      alwaysShow="true" />.
    swimmingExpert: Terminer l'activité <object id="activity-swimming_(expert)-95a78afb-79f0-431c-b7aa-062659d9ec87"
      alwaysShow="true" /><numberProgress current="{current}" max="{max}" /> fois.
    underwaterBasketweaving: Marcher <numberProgress current="{current}" max="{max}"
      /> pas en faisant l'activité <object id="activity-underwater_basket_weaving-7ba725a2-d147-437c-98bf-5a9f58d68b65"
      alwaysShow="true" /> à <object id="location-fertile_shallows-6561e4b5-fce3-4307-a641-86ca5aee36d6"
      alwaysShow="true" />.
    beginnerSkydisc: Terminer l'activité <object id="activity-frisbee_golfing_(beginner)-0fb41f4d-f46b-4a6d-acdf-f2525654c714"
      alwaysShow="true" /> à <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a"
      alwaysShow="true" /><numberProgress current="{current}" max="{max}" /> fois.
  factionReputations:
    syrenthiaReputation: Avoir <numberProgress current="{current}" max="{max}" /><realm
      realm="faction-syrenthia-6e9359fa-597b-4448-9df5-cc3fff9a5108" /> réputation
      de faction.
    trellinReputation: Avoir <numberProgress current="{current}" max="{max}" /><realm
      realm="faction-trellin-239a0ad8-3812-4f2a-9c11-1c312490249b" /> réputation de
      faction.
    erdwiseReputation: Avoir <numberProgress current="{current}" max="{max}" /><realm
      realm="faction-erdwise-697ae8a6-491e-46fd-8a05-4b744f9630eb" /> réputation de
      faction.
    halflingRebelsReputation: Avoir <numberProgress current="{current}" max="{max}"
      /><realm realm="faction-halfling_rebels-394eaff8-2749-4473-949c-80da531a415e"
      /> réputation de faction.
    jarvoniaReputation: Avoir <numberProgress current="{current}" max="{max}" /><realm
      realm="faction-jarvonia-1b061315-a63d-4dc1-a8ba-10902a83c5db" /> réputation
      de faction.
