singulars:
  haveCoins:
    text: Avoir <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> pièces.
  mainSkill:
    text: En pratiquant la compétence <skill skill="{skill}"/>
  itemInInventory:
    text: Avoir <item id="{item}"/> dans votre inventaire.
  skillLevel:
    text: Au moins <skill skill="{skill}" level="{level}" needed/>
  traveling:
    text: En voyageant
  itemAnywhereWithYou:
    text: Avoir <item id="{item}"/> avec vous.
  itemAnywhere:
    text: Avoir <item id="{item}"/>.
