singulars:
  mainSkill:
    text: Vid bruk av <skill skill="{skill}"/>
  skillLevel:
    text: Minst <skill skill="{skill}" level="{level}" needed/>
  traveling:
    text: Under resan
  itemAnywhereWithYou:
    text: Ha föremål <item id="{item}"/> med dig.
  itemEquipped:
    text: Ha föremålet <item id="{item}"/> utrustat.
  itemInInventory:
    text: Ha föremålet <item id="{item}"/> i ditt inventarie.
  itemAnywhere:
    text: Ha föremålet <item id="{item}"/>.
  distinctItemsEquippedKeyword:
    text: Kräver <numberProgress current="{current}" max="{max}" /> unika <object
      id="{obj}" /> utrustade.
  characterLevel:
    text: Ha karaktärnivå <numberProgress current="{current}" max="{max}" />.
  unlocked:
    text: Har låst upp <object id="{obj}" alwaysShow="true" />.
  achievementPointsPercent:
    text: Har <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> prestationspoäng ({percentage}% av total).
  haveCoins:
    text: Ha <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> mynt.
  minimumSkillLevel:
    text: Har varje egenskap på minst nivå <numberProgress current="{current}" max="{max}"
      />.
  overencumbered:
    text: Ha ditt inventarium över gränsen (Överlastad).
  totalSteps:
    text: Ha gått <numberProgress current="{current}" max="{max}" /> steg totalt.
  achievementPoints:
    text: Har <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> prestationspoäng.
  levelUpSkills:
    text: Höj nivån på dina egenskaper <numberProgress current="{current}" max="{max}"
      /> gånger.
