singulars:
  smithing:
    basicForge:
      name: Grundläggande smedja
      desc: En nybörjarsmedja, perfekt för att tillverka enklare föremål.
    advancedForge:
      name: Avancerad smedja
      desc: En mer avancerad smedja, perfekt för att skapa mer avancerade och högkvalitativa
        föremål.
    frozenForge:
      name: Frusen smedja
      desc: En smedja av is, med små pingvinristningar över hela den.
    underwaterForge:
      name: Undervattenssmedja (Grundläggande)
      desc: Undervattenssmedjan drivs av varma ånggejsrar som ger tillräckligt med
        värme för att smälta metall.
    cursedForge:
      name: Förbannad smedja (Avancerad)
      desc: Den förbannade smedjan hämtar sina kraftiga lågor från andarna omkring
        den, men tyvärr har det ett pris. Bäst att inte använda den för mycket.
    heatstrokeMetalworks:
      name: Värmeslagets metallverk (Avancerad)
      desc: Den starka och hyllade smedjan i Myriadianska Arken. Den utstrålar en
        värme som du känner omkring den även i öknen.
  cooking:
    basicKitchen:
      desc: Ett enkelt kök, där du kan laga enkla och näringsrika måltider.
      name: Grundläggande kök
    eberhartMansionKitchen:
      name: Eberharts herrgårdskök (Avancerad)
      desc: Eberhartfamiljen ger till dem som ger till andra. Bevis på ditt engagemang
        i det lokala soppköket räcker mer än väl för att de ska öppna sina dörrar
        och låta dig använda deras gemensamma köksutrymme.
    advancedKitchen:
      name: Avancerat kök
      desc: Ett välutrustat kök, lämpligt för gourmetmatlagning och kulinariska experiment.
    underwaterKitchen:
      name: Undervattenskök (Grundläggande)
      desc: Det här köket är utrustat med olika matlagningsverktyg anpassade för att
        laga mat under vatten.
    cursedKitchen:
      name: Förbannat kök (Avancerat)
      desc: Det förbannade köket har allt du behöver för att laga en rätt, om bara
        spisen höll en jämn temperatur och vattnet fortsatte att rinna.
    azurazeraKitchen:
      name: Alight-kök (Grundläggande)
      desc: Ett gemenskapskök där några kockar försöker dela med sig av sina matlagningskunskaper
        till varandra för att bli bättre.
  crafting:
    tidalWorkshop:
      desc: En verkstad som ständigt påverkas av strömmen. Den har alla verktyg som
        behövs för att tillverka saker.
      name: Tidvattenverkstad (Avancerad)
    basicWorkshop:
      name: Grundläggande verkstad
      desc: En enkel verkstad, utformad för att tillverka enkla och praktiska föremål.
    advancedWorkshop:
      name: Advancerad verkstad
      desc: En avancerad verkstad, utrustad för att tillverka komplexa och mångsidiga
        skapelser.
