singulars:
  smithing:
    basicForge:
      name: Grundläggande smedja
      desc: En nybörjarsmedja, perfekt för att tillverka enklare föremål.
    advancedForge:
      name: Avancerad smedja
      desc: En mer avancerad smedja, perfekt för att skapa mer avancerade och högkvalitativa
        föremål.
    frozenForge:
      name: Frusen smedja
      desc: En smedja av is, med små pingvinristningar över hela den.
    underwaterForge:
      name: Undervattenssmedja (Grundläggande)
      desc: Undervattenssmedjan drivs av varma ånggejsrar som ger tillräckligt med
        värme för att smälta metall.
    cursedForge:
      name: Förbannad smedja (Avancerad)
      desc: Den förbannade smedjan hämtar sina kraftiga lågor från andarna omkring
        den, men tyvärr har det ett pris. Bäst att inte använda den för mycket.
    heatstrokeMetalworks:
      name: Värmeslagets metallverk (Avancerad)
      desc: Den starka och hyllade smedjan i Myriadianska Arken. Den utstrålar en
        värme som du känner omkring den även i öknen.
  cooking:
    basicKitchen:
      desc: Ett enkelt kök, där du kan laga enkla och näringsrika måltider.
      name: Grundläggande kök
    eberhartMansionKitchen:
      name: Eberharts herrgårdskök (Avancerad)
      desc: Eberhartfamiljen ger till dem som ger till andra. Bevis på ditt engagemang
        i det lokala soppköket räcker mer än väl för att de ska öppna sina dörrar
        och låta dig använda deras gemensamma köksutrymme.
    advancedKitchen:
      name: Avancerat kök
      desc: Ett välutrustat kök, lämpligt för gourmetmatlagning och kulinariska experiment.
    underwaterKitchen:
      name: Undervattenskök (Grundläggande)
      desc: Det här köket är utrustat med olika matlagningsverktyg anpassade för att
        laga mat under vatten.
    cursedKitchen:
      name: Förbannat kök (Avancerat)
      desc: Det förbannade köket har allt du behöver för att laga en rätt, om bara
        spisen höll en jämn temperatur och vattnet fortsatte att rinna.
    azurazeraKitchen:
      name: Alight-kök (Grundläggande)
      desc: Ett gemenskapskök där några kockar försöker dela med sig av sina matlagningskunskaper
        till varandra för att bli bättre.
  crafting:
    tidalWorkshop:
      desc: En verkstad som ständigt påverkas av strömmen. Den har alla verktyg som
        behövs för att tillverka saker.
      name: Tidvattenverkstad (Avancerad)
    basicWorkshop:
      name: Grundläggande verkstad
      desc: En enkel verkstad, utformad för att tillverka enkla och praktiska föremål.
    advancedWorkshop:
      name: Advancerad verkstad
      desc: En avancerad verkstad, utrustad för att tillverka komplexa och mångsidiga
        skapelser.
    cursedWorkshop:
      name: Förbannad verkstad (Avancerad)
      desc: Den förbannade verkstaden verkar vanlig vid första anblicken, men den
        luktar svavel, förruttnelse och en antydan av citron. Den är verkligen förbannad.
  trinketry:
    erdwissTrinketryFactory:
      name: Erdwiss krimskramsfabrik (Avancerad)
      desc: ETF har några av de finaste maskinerna som importerats från Stormhärd
        för att slipa ädelstenar.
    basicTrinketryBench:
      name: Enkel krimskramsbänk
      desc: En arbetsbänk, utformad för att slipa ädelstenar och göra enkla krimskrams.
    granularFacetingFacility:
      name: Granulära fasetteringsanläggningen (Avancerad)
      desc: En enastående krimskramsanläggning som samlar några av de främsta utövarna
        av ädelstenskonsten.
    ruinedTrinketryBench:
      name: Förfallen krimskramsbänk (Grundläggande)
      desc: I ruinerna av Vinterslut står en uråldrig krimskramsbänk täckt av mossa
        och svamp.
    advancedTrinketryBench:
      name: Avancerad krimskramsbänk
      desc: En anspråkslös bänk, fylld med linser, sandpapper och andra verktyg som
        en gesäll i krimskramsmakeri behöver.
  tailoring:
    advancedLoom:
      desc: En välutrustad verkstad med en toppmodern vävstol och ett elegant sybord,
        fylld med ett noga utvalt urval av förstklassiga tyger och specialverktyg
        – perfekt för erfarna skräddare som vill skapa utsökta plagg.
      name: Avancerad vävstol
    basicLoom:
      name: Grundläggande vävstol
      desc: En anspråkslös verkstad med en robust vävstol och ett välanvänt sybord,
        fylld med en blandning av tyger och verktyg – perfekt för blivande skräddare
        som vill lära sig konsten att sy kläder.
  misc:
    mysteriousMerchant:
      name: Hemlighetsfulle Handlaren
      desc: En skum figur som erbjuder exotiska tjänster.
  carpentry:
    underwaterSawmill:
      desc: Ett sågverk som är perfekt för att arbeta med träliknande koraller, men
        som också har verktyg för att göra om alla stockar till plankor.
      name: Undervattenssågverk (Grundläggande)
    basicSawmill:
      name: Grundläggande sågverk
      desc: En enkel träbearbetningsanläggning där stockar förvandlas till simpelt
        virke.
    advancedSawmill:
      name: Avancerat sågverk
      desc: Ett avancerat träbearbetningssågverk som kan producera virke av högre
        kvalitet med precision och effektivitet.
    barbantokSawmill:
      name: Barbantoks sågverk (Grundläggande)
      desc: Ett sågverk som sägs hemsökas av Barbantoks spöke, en legendarisk snickare
        känd för sitt enastående hantverk.
    sawInHalfMill:
      name: Halveringssågverk (Avancerat)
      desc: Småfolkets sågverk är ett tekniskt underverk, som drivs av vattenflödet
        genom en undervattensakvedukt och ett avancerat vattenhjul.
    cursedSawmill:
      name: Förbannat sågverk (Avancerat)
      desc: Det förbannade sågverket snurrar sågbladet så snabbt att du fruktar att
        det ska slita sig loss. Ibland känns det som att det dras mot dig snarare
        än att stockarna sågas.
  cosmetics:
    barber:
      name: Barberare
      desc: En barberare som kan ge dig en ny frisyr.
    wardrobe:
      name: Garderob
      desc: Tillgång till din garderob, så att du kan ändra ditt utseende till vad
        du än äger.
maps:
  tiers:
    "basic": Grundläggande
    "advanced": Avancerad
    "legendary": Legendarisk
    "mythic": Mystisk
