singulars:
  achievementPoints:
    text: <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> başarım puanın olsun.
  uniques:
    intermediateCrossCountry: <object 
      id="activity-cross-country_skiing_(intermediate)-42788047-6cc3-4711-88be-999e9504fc2a"
      alwaysShow="true" /> faaliyetini <numberProgress current="{current}" max="{max}"
      /> kere tamamla.
    beginnerCrossCountry: <object 
      id="activity-cross-country_skiing_(beginner)-fc421940-d63a-402f-aa50-26cc2efea4d3"
      alwaysShow="true" /> faaliyetini <numberProgress current="{current}" max="{max}"
      /> kere tamamla.
    firewoodMaking: <object id="activity-firewood_making-407263a4-4ee1-4383-a624-2a7ed70c4b10"
      alwaysShow="true" /> faaliyetini <numberProgress current="{current}" max="{max}"
      /> kere tamamla.
    woodCarving: <object id="activity-wood_carving-af675674-c972-4e2e-80fe-1501b972e353"
      alwaysShow="true" /> faaliyetini <numberProgress current="{current}" max="{max}"
      /> kere tamamla.
    intermediateShipRepair: <object id="activity-ship_repair_(intermediate)-44f2f2e7-bef1-437f-ac35-bf64b97cc249"
      alwaysShow="true" /> faaliyetini <numberProgress current="{current}" max="{max}"
      /> kere tamamla.
  mainSkill:
    text: <skill skill="{skill}"/> yaparken
  itemAnywhereWithYou:
    text: <item id="{item}"/> bulundur.
  distinctItemsEquippedKeyword:
    text: <numberProgress current="{current}" max="{max}" /> adet <object id="{obj}"
      /> kuşan.
  gear:
    beginnerSkydisc: <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a"
      alwaysShow="true" /> konumunda <object id="activity-frisbee_golfing_(beginner)-0fb41f4d-f46b-4a6d-acdf-f2525654c714"
      alwaysShow="true" /> faaliyetini <numberProgress current="{current}" max="{max}"
      /> kere tamamla.
    underwaterBasketweaving: <object id="location-fertile_shallows-6561e4b5-fce3-4307-a641-86ca5aee36d6"
      alwaysShow="true" /> konumunda <object id="activity-underwater_basket_weaving-7ba725a2-d147-437c-98bf-5a9f58d68b65"
      alwaysShow="true" /> faaliyeti yaparken <numberProgress current="{current}"
      max="{max}" /> adım at.
    tinkering: <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a"
      alwaysShow="true" /> konumunda <object id="activity-tinkering-cb2a8773-06d0-4661-9708-2bef5768119e"
      /> faaliyeti yaparken <numberProgress current="{current}" max="{max}" /> adım
      at.
    iceSculpting: <object id="location-frusenholm-5ddb0735-4582-4858-80a0-7489f1b043a2"
      alwaysShow="true" /> konumunda <object id="activity-ice_sculpting-2b0be0f5-69d5-4205-922d-c5a02c056cab"
      alwaysShow="true" /> faaliyeti yaparken <numberProgress current="{current}"
      max="{max}" /> adım at.
    swimmingExpert: <object id="activity-swimming_(expert)-95a78afb-79f0-431c-b7aa-062659d9ec87"
      alwaysShow="true" /> faaliyetini <numberProgress current="{current}" max="{max}"
      /> kere tamamla.
  skillLevel:
    text: En az <skill skill="{skill}" level="{level}" gerekli/>
  traveling:
    text: Seyahat ederken
  itemInInventory:
    text: Envanterinde <item id="{item}"/> bulundur.
  itemEquipped:
    text: <item id="{item}"/> kuşan.
  itemAnywhere:
    text: <item id="{item}"/> bulundur.
  totalSteps:
    text: Toplam <numberProgress current="{current}" max="{max}" /> adım yürü.
  characterLevel:
    text: Karakter seviyen <numberProgress current="{current}" max="{max}" /> olsun.
  unlocked:
    text: <object id="{obj}" alwaysShow="true" /> açmış ol.
  achievementPointsPercent:
    text: <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> başarım puanın olsun (Toplamın %{percentage}'si).
  haveCoins:
    text: <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> akçen olsun.
  minimumSkillLevel:
    text: Her becerin en az <numberProgress current="{current}" max="{max}" /> seviye
      olsun.
  levelUpSkills:
    text: Becerilerini <numberProgress current="{current}" max="{max}" /> kere seviye
      atlat.
  exploreRealm:
    text: <object id="{obj}" alwaysShow="true" /> diyarını tamamen keşfet. <numberProgress
      current="{current}" max="{max}" />.
  overencumbered:
    text: Envanterin dolup taşmış olsun.
  haveBankStacks:
    text: Bankanda <numberProgress current="{current}" max="{max}" /> eşya yığını
      bulundur.
  activityType:
    singleKeyword: <object id="{obj}" /> faaliyeti yaparken.
  realm:
    text: <realm realm="{realm}" /> diyarındayken.
  locationHasKeywords:
    text: <object id="{obj}" /> konumundayken.
  factionReputations:
    jarvoniaReputation: <numberProgress current="{current}" max="{max}" /> <realm
      realm="faction-jarvonia-1b061315-a63d-4dc1-a8ba-10902a83c5db" /> diyar itibarın
      olsun.
    trellinReputation: <numberProgress current="{current}" max="{max}" /> <realm realm="faction-trellin-239a0ad8-3812-4f2a-9c11-1c312490249b"
      /> diyar itibarın olsun.
    erdwiseReputation: <numberProgress current="{current}" max="{max}" /> <realm realm="faction-erdwise-697ae8a6-491e-46fd-8a05-4b744f9630eb"
      /> diyar itibarın olsun.
    halflingRebelsReputation: <numberProgress current="{current}" max="{max}" /> <realm
      realm="faction-erdwise-697ae8a6-491e-46fd-8a05-4b744f9630eb" /> diyar itibarın
      olsun.
    syrenthiaReputation: <numberProgress current="{current}" max="{max}" /> <realm
      realm="faction-syrenthia-6e9359fa-597b-4448-9df5-cc3fff9a5108" /> diyar itibarın
      olsun.
