singulars:
  achievementPoints:
    text: <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> başarım puanına ulaş.
  uniques:
    intermediateCrossCountry: <object 
      id="activity-cross-country_skiing_(intermediate)-42788047-6cc3-4711-88be-999e9504fc2a"
      alwaysShow="true" /> faaliyetini <numberProgress current="{current}" max="{max}"
      /> kere tamamla.
    beginnerCrossCountry: <object 
      id="activity-cross-country_skiing_(beginner)-fc421940-d63a-402f-aa50-26cc2efea4d3"
      alwaysShow="true" /> faaliyetini <numberProgress current="{current}" max="{max}"
      /> kere tamamla.
    firewoodMaking: <object id="activity-firewood_making-407263a4-4ee1-4383-a624-2a7ed70c4b10"
      alwaysShow="true" /> faaliyetini <numberProgress current="{current}" max="{max}"
      /> kere tamamla.
    woodCarving: <object id="activity-wood_carving-af675674-c972-4e2e-80fe-1501b972e353"
      alwaysShow="true" /> faaliyetini <numberProgress current="{current}" max="{max}"
      /> kere tamamla.
    intermediateShipRepair: <object id="activity-ship_repair_(intermediate)-44f2f2e7-bef1-437f-ac35-bf64b97cc249"
      alwaysShow="true" /> faaliyetini <numberProgress current="{current}" max="{max}"
      /> kere tamamla.
    searchTeam: Kara Gözlü Zirve <object id="activity-black_eye_peak_search_team-d1ad835f-0898-4fc7-8f0a-4b0626d95306"
      alwaysShow="true" /> faaliyetini <object id="location-horn_of_respite-1661d247-11f1-49eb-b927-6e59c8fd7774"
      alwaysShow="true" /> konumunda <numberProgress current="{current}" max="{max}"
      /> kere tamamla.
    wreckDiving: <object id="activity-wreck_diving-12e980cd-058a-42c4-8358-ba7afe1c319c"
      alwaysShow="true" /> faaliyetini <numberProgress current="{current}" max="{max}"
      /> kere tamamla.
    wraithwaterBankRebuild: <object id="2808f754-9d31-4243-a711-7214a2a1c7b7" alwaysShow="true"
      />.
    notUnderwater: <object id="location_underwater" /> konumunda değilken.
    notAgility: <skill skill="agility"/> yapmıyorken.
    smeltRecipe: <object id="recipe_smelting" /> tarifi uygularken.
  mainSkill:
    text: <skill skill="{skill}"/> yaparken.
  itemAnywhereWithYou:
    text: Yanında <item id="{item}"/> bulundur.
  distinctItemsEquippedKeyword:
    text: <numberProgress current="{current}" max="{max}" /> adet <object id="{obj}"
      /> kuşan.
  gear:
    beginnerSkydisc: <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a"
      alwaysShow="true" /> konumunda <object id="activity-frisbee_golfing_(beginner)-0fb41f4d-f46b-4a6d-acdf-f2525654c714"
      alwaysShow="true" /> faaliyetini <numberProgress current="{current}" max="{max}"
      /> kere tamamla.
    underwaterBasketweaving: <object id="location-fertile_shallows-6561e4b5-fce3-4307-a641-86ca5aee36d6"
      alwaysShow="true" /> konumunda <numberProgress current="{current}" max="{max}"
      /> kere <object id="activity-underwater_basket_weaving-7ba725a2-d147-437c-98bf-5a9f58d68b65"
      alwaysShow="true" /> faaliyeti tamamla.
    tinkering: <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a"
      alwaysShow="true" /> konumunda <numberProgress current="{current}" max="{max}"
      /> kere <object id="activity-tinkering-cb2a8773-06d0-4661-9708-2bef5768119e"
      /> faaliyeti tamamla.
    iceSculpting: <object id="location-frusenholm-5ddb0735-4582-4858-80a0-7489f1b043a2"
      alwaysShow="true" /> konumunda <numberProgress current="{current}" max="{max}"
      /> kere <object id="activity-ice_sculpting-2b0be0f5-69d5-4205-922d-c5a02c056cab"
      alwaysShow="true" /> faaliyeti tamamla.
    swimmingExpert: <object id="activity-swimming_(expert)-95a78afb-79f0-431c-b7aa-062659d9ec87"
      alwaysShow="true" /> faaliyetini <numberProgress current="{current}" max="{max}"
      /> kere tamamla.
    sledding: <object id="activity-sledding-290bfd6c-3bb1-47c6-bf60-880c1d4a5148"
      /> faaliyeti yaparken.
  skillLevel:
    text: En az <skill skill="{skill}" level="{level}" gerekli/>.
  traveling:
    text: Seyahat ederken.
  itemInInventory:
    text: Envanterinde <item id="{item}"/> bulundur.
  itemEquipped:
    text: <item id="{item}"/> kuşan.
  itemAnywhere:
    text: <item id="{item}"/> bulundur.
  totalSteps:
    text: Toplam <numberProgress current="{current}" max="{max}" /> adım yürü.
  characterLevel:
    text: <numberProgress current="{current}" max="{max}" /> karakter seviyesine ulaş.
  unlocked:
    text: <object id="{obj}" alwaysShow="true" /> açmış ol.
  achievementPointsPercent:
    text: <icon i="achievement point"/> <numberProgress current="{current}" max="{max}"
      /> başarım puanına ulaş. (Toplamın %{percentage} kadarı).
  haveCoins:
    text: <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> akçe biriktir.
  minimumSkillLevel:
    text: Bütün becerilerini <numberProgress current="{current}" max="{max}" /> seviyeye
      ulaştır.
  levelUpSkills:
    text: Becerilerinin seviyesini <numberProgress current="{current}" max="{max}"
      /> kere yükselt.
  exploreRealm:
    text: <object id="{obj}" alwaysShow="true" /> diyarını tamamen keşfet. <numberProgress
      current="{current}" max="{max}" />.
  overencumbered:
    text: Envanterini doldurup taşır.
  haveBankStacks:
    text: Bankanda <numberProgress current="{current}" max="{max}" /> eşya yığını
      bulundur.
  activityType:
    singleKeyword: <object id="{obj}" /> faaliyeti yaparken.
  realm:
    text: <realm realm="{realm}" /> diyarındayken.
  locationHasKeywords:
    text: <object id="{obj}" /> konumdayken.
  factionReputations:
    jarvoniaReputation: <numberProgress current="{current}" max="{max}" /> <realm
      realm="faction-jarvonia-1b061315-a63d-4dc1-a8ba-10902a83c5db" /> diyar itibarına
      ulaş.
    trellinReputation: <numberProgress current="{current}" max="{max}" /> <realm realm="faction-trellin-239a0ad8-3812-4f2a-9c11-1c312490249b"
      /> diyar itibarına ulaş.
    erdwiseReputation: <numberProgress current="{current}" max="{max}" /> <realm realm="faction-erdwise-697ae8a6-491e-46fd-8a05-4b744f9630eb"
      /> diyar itibarına ulaş.
    halflingRebelsReputation: <numberProgress current="{current}" max="{max}" /><realm
      realm="faction-halfling_rebels-394eaff8-2749-4473-949c-80da531a415e" /> diyar
      itibarına ulaş.
    syrenthiaReputation: <numberProgress current="{current}" max="{max}" /> <realm
      realm="faction-syrenthia-6e9359fa-597b-4448-9df5-cc3fff9a5108" /> diyar itibarına
      ulaş.
  haveItemStack:
    text: <object id="{obj}" alwaysShow="true" /> eşyasından <numberProgress current="{current}"
      max="{max}" /> sayılı bir yığın oluştur.
  service:
    text: En az <serviceTier tier="{tier}" /> veya daha yüksek <object id="{obj}"
      /> hizmeti gerekli.
  maps:
    jarvoniaMap: <object id="item-map_of_jarvonia-86ba96b3-a845-4f5c-a054-04ec5146fb25"
      /> gerekli.
    syrenthiaMap: <object id="65979ee2-f98a-41c3-9f12-8858000017a3" /> gerekli.
    trellinMap: <object id="item-map_of_gdte-b28951b2-2cac-4e53-b6f1-bc2030590433"
      /> gerekli.
    erdwiseMap: <object id="fa277527-585b-4a1d-bc73-a25fe1195017" /> gerekli.
    halflingMap: <object id="f1a9e370-fd69-4a49-92c0-c83475a896ab" /> gerekli.
  mainSkillType:
    text: <skillType type="{type}"/> faaliyetleri yaparken.
  itemQualityEquipped:
    text: En az <numberProgress current="{current}" max="{max}" /> tane <itemQuality
      quality="{quality}" type="{type}"/> eşya kuşan.
    withoutType: En az <numberProgress current="{current}" max="{max}" /> tane <itemQuality
      quality="{quality}" type="crafted"/> veya <itemQuality quality="{quality}" type="loot"/>
      eşya kuşan.
  keywordEquipped:
    text: <object id="{obj}" /> kuşan.
  keywordWithLevelEquipped:
    text: En az <numberProgress current="{current}" max="{max}" /> seviye <skill skill="{skill}"/>
      gerektiren <object id="{obj}" /> kuşan.
  totalSkillLevel:
    text: Toplam <numberProgress current="{current}" max="{max}" /> beceri seviyesine
      ulaş.
  itemsGained:
    text: <object id="{obj}" /> kazan. <numberProgress current="{current}" max="{max}"
      />.
  petTotalLevels:
    text: Toplam <numberProgress current="{current}" max="{max}" /> evcil hayvan seviyesine
      ulaş.
  abilityAvailable:
    text: <object id="{obj}" /> yeteneği mevcutken.
  petWithKeyword:
    text: <object id="{obj}" /> sahibi ol. <numberProgress current="{current}" max="{max}"
      />
    textDistinct: Farklı türde <object id="{obj}" /> sahibi ol. <numberProgress current="{current}"
      max="{max}" />
  hasPet:
    text: <object id="{obj}" /> sahibi ol.
  petAmount:
    text: <numberProgress current="{current}" max="{max}" /> evcil hayvan sahiplen.
  petHighestLevel:
    text: En az <numberProgress current="{current}" max="{max}" /> seviye evcil hayvan
      sahibi ol.
  itemsWithKeywordCrafted:
    text: <object id="{obj}" /> eşya üret. <numberProgress current="{current}" max="{max}"
      />
  serviceKeywords:
    text: <serviceTier tier="{tier}" /> {objects} veya daha yüksek hizmet gerekli.
  currentService:
    text: En az <serviceTier tier="{tier}" /> veya daha yüksek <object id="{obj}"
      /> hizmeti gerekli. <object id="{currentObj}" icon="false" /> kullanamazsın.
  currentServiceKeywords:
    text: En az <serviceTier tier="{tier}" /> veya daha yüksek {objects} hizmeti gerekli.
      <object id="{currentObj}" icon="false" /> kullanamazsın.
  recipeType:
    text: <object id="{obj}" /> tarifi uygularken.
