singulars:
  minimumSkillLevel:
    text: Достигните уровня не ниже <numberProgress current="{current}" max="{max}"
      /> для каждого навыка.
  distinctItemsEquippedKeyword:
    text: Экипируйте <numberProgress current="{current}" max="{max}" /> <object id="{obj}"
      />.
  gear:
    tinkering: Сделано <numberProgress current="{current}" max="{max}" /> шагов в
      <object id="activity-tinkering-cb2a8773-06d0-4661-9708-2bef5768119e" /> Активность
      в <object id="location-barbantok-018aaeeb-5b51-4043-94b7-28fa7dcb7b7a" alwaysShow="true"
      />.
    swimmingExpert: Активность <object id="activity-swimming_(expert)-95a78afb-79f0-431c-b7aa-062659d9ec87"
      alwaysShow="true" /> выполнена <numberProgress current="{current}" max="{max}"
      /> раз.
  itemInInventory:
    text: <item id="{item}"/> должен быть в инвентаре.
  haveItemStack:
    text: У вас есть стек предметов <object id="{obj}" alwaysShow="true" /> размером
      в <numberProgress current="{current}" max="{max}" />.
  mainSkill:
    text: Выполняя <skill skill="{skill}"/>
  traveling:
    text: В пути
  itemAnywhereWithYou:
    text: Имей <item id="{item}"/>при себе.
  itemEquipped:
    text: <item id="{item}"/> должен быть экипирован.
  totalSteps:
    text: Всего пройдено <numberProgress current="{current}" max="{max}" /> шагов.
  characterLevel:
    text: Уровень персонажа <numberProgress current="{current}" max="{max}" />.
  itemAnywhere:
    text: Предмет <item id="{item}"/>.
  unlocked:
    text: Разблокирован <object id="{obj}" alwaysShow="true" />.
  achievementPointsPercent:
    text: Всего <icon i="achievement point"/> <numberProgress current="{current}"
      max="{max}" /> очков достижений ({percentage}% от общего количества).
  haveCoins:
    text: У вас есть <icon i="money small"/> <numberProgress current="{current}" max="{max}"
      /> монет.
  levelUpSkills:
    text: Повысьте уровень своих навыков <numberProgress current="{current}" max="{max}"
      /> раз.
  overencumbered:
    text: Инвентарь переполнен.
  exploreRealm:
    text: Полностью изучите <object id="{obj}" alwaysShow="true" />. <numberProgress
      current="{current}" max="{max}" />.
  haveBankStacks:
    text: У вас <numberProgress current="{current}" max="{max}" /> стаков в банке.
  activityType:
    singleKeyword: Во время выполнения активности <object id="{obj}" />.
  realm:
    text: Находясь в <realm realm="{realm}" />.
  locationHasKeywords:
    text: Находясь в <object id="{obj}" />.
  uniques:
    intermediateCrossCountry: Выполните активность <object 
      id="activity-cross-country_skiing_(intermediate)-42788047-6cc3-4711-88be-999e9504fc2a"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> раз.
    woodCarving: Выполните активность <object id="activity-wood_carving-af675674-c972-4e2e-80fe-1501b972e353"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> раз.
    intermediateShipRepair: Выполните активность <object id="activity-ship_repair_(intermediate)-44f2f2e7-bef1-437f-ac35-bf64b97cc249"
      alwaysShow="true" /><numberProgress current="{current}" max="{max}" /> раз.
    beginnerCrossCountry: Выполните активность <object 
      id="activity-cross-country_skiing_(beginner)-fc421940-d63a-402f-aa50-26cc2efea4d3"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> раз.
    firewoodMaking: Выполните активность <object id="activity-firewood_making-407263a4-4ee1-4383-a624-2a7ed70c4b10"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> раз.
    searchTeam: Выполните активность "Пик чёрного глаза" <object id="activity-black_eye_peak_search_team-d1ad835f-0898-4fc7-8f0a-4b0626d95306"
      alwaysShow="true" /> в <object id="location-horn_of_respite-1661d247-11f1-49eb-b927-6e59c8fd7774"
      alwaysShow="true" /> <numberProgress current="{current}" max="{max}" /> раз.
  skillLevel:
    text: Требуется уровень навыка <skill skill="{skill}" level="{level}"/>
  achievementPoints:
    text: Всего <icon i="achievement point"/> <numberProgress current="{current}"
      max="{max}" /> очков достижений.
  service:
    text: Требуется <serviceTier tier="{tier}" /> <object id="{obj}" /> или лучше.
