singulars:
  smithing:
    frozenForge:
      name: 冰霜熔炉
      desc: 用冰制成的熔炉，刻满了小企鹅。
    advancedForge:
      desc: 更加精密的熔炉，非常适合制作复杂且高品质的道具。
      name: 高级熔炉
    basicForge:
      desc: 入门级别的熔炉，适合制作简单的道具。
      name: 初级熔炉
    underwaterForge:
      name: 水下熔炉（初级）
      desc: 水下熔炉由热蒸汽喷泉驱动，提供足够的热量来熔化金属。
  cooking:
    basicKitchen:
      name: 初级厨房
      desc: 一个朴素的厨房，您可以在这里准备简单又健康的饭菜。
    advancedKitchen:
      name: 高级厨房
      desc: 设备齐全的厨房，适合精致烹饪与创意料理探索。
    underwaterKitchen:
      name: 水下厨房（初级）
      desc: 厨房配备了各种适合在水下烹饪的工具。
    eberhartMansionKitchen:
      name: 埃伯哈特大厦厨房（高级）
      desc: 艾伯哈特家族会帮助那些帮助他人的人。你在当地施粥所所做出的贡献证明了你的热心肠，足以让他们敞开大门，让你使用他们的厨房。
  crafting:
    basicWorkshop:
      desc: 入门级的工作室设置，用于制作简单实用的物品。
      name: 初级工作室
    advancedWorkshop:
      name: 高级工作室
      desc: 先进的工作室，配备制作复杂且具备多功能的设备。
    tidalWorkshop:
      name: 潮汐工作室（高级）
      desc: 一个始终受到潮流波流的工坊。它拥有制作物品所需的所有工具。
  carpentry:
    basicSawmill:
      name: 初级锯木厂
      desc: 一个简陋的木材加工厂，能将原木加工成基础木材。
    advancedSawmill:
      name: 高级锯木厂
      desc: 先进的木材加工厂，能够精确、高效地生产出更高质量的木材。
    underwaterSawmill:
      name: 水下锯木厂（初级）
      desc: 此锯木厂不仅适合加工木质珊瑚，还提供将任何原木加工成木板的设备。
  cosmetics:
    barber:
      name: 理发师
      desc: 可以帮你打造不同发型的理发师。
    wardrobe:
      name: 衣柜
      desc: 访问你的衣柜，就可以使用你拥有的任何外观来改变外貌。
maps:
  tiers:
    "basic": 基础
    "advanced": 高级
    "legendary": 传说
    "mythic": 神话
