singulars:
  smithing:
    frozenForge:
      name: 冰霜熔炉
      desc: 用冰制成的熔炉，刻满了小企鹅。
    advancedForge:
      desc: 更加精密的熔炉，非常适合制作复杂且高品质的物品。
      name: 高级熔炉
    basicForge:
      desc: 入门级别的熔炉，适合制作简单的物品。
      name: 初级熔炉
    underwaterForge:
      name: 水下熔炉（初级）
      desc: 水下熔炉由热蒸汽喷泉驱动，提供足够的热量来熔化金属。
  cooking:
    basicKitchen:
      name: 初级厨房
      desc: 一个朴素的厨房，您可以在这里准备简单又健康的饭菜。
    advancedKitchen:
      name: 高级厨房
      desc: 设备齐全的厨房，适合精致烹饪与创意料理探索。
    underwaterKitchen:
      name: 水下厨房（初级）
      desc: 厨房配备了各种适合在水下烹饪的工具。
    eberhartMansionKitchen:
      name: 埃伯哈特大厦厨房（高级）
      desc: 艾伯哈特家族会帮助那些帮助他人的人。你在当地施粥所所做出的贡献证明了你的热心肠，足以让他们敞开大门，让你使用他们的厨房。
  crafting:
    basicWorkshop:
      desc: 入门级的工坊，用于制作简单实用的物品。
      name: 初级工坊
    advancedWorkshop:
      name: 高级工坊
      desc: 非常高级的工坊，配备制作复杂且具备多功能的设备。
    tidalWorkshop:
      name: 潮汐工坊（高级）
      desc: 一个始终受到潮流波流的工坊。它拥有制作物品所需的所有工具。
  carpentry:
    basicSawmill:
      name: 初级锯木厂
      desc: 一个简陋的木材加工厂，能将原木加工成基础木材。
    advancedSawmill:
      name: 高级锯木厂
      desc: 先进的木材加工厂，能够精确、高效地生产出更高质量的木材。
    underwaterSawmill:
      name: 水下锯木厂（初级）
      desc: 此锯木厂不仅适合加工木质珊瑚，还提供将任何原木加工成木板的设备。
    sawInHalfMill:
      name: 断锯木厂（高级）
      desc: 这座半身人锯木厂的工程设计堪称奇迹，依靠水流通过建筑下方的水下管道来驱动与其相连的复杂水轮系统，为工厂提供动力。
    barbantokSawmill:
      name: 巴本托克锯木厂（初级）
      desc: 据说这座锯木厂仍被巴本托克的鬼魂所纠缠着，巴班托克生前是位以其卓越工艺闻名的传奇木匠。
  cosmetics:
    barber:
      name: 理发师
      desc: 可以帮你打造不同发型的理发师。
    wardrobe:
      name: 衣柜
      desc: 访问你的衣柜，就可以使用你拥有的外观装扮来改变外貌。
  tailoring:
    advancedLoom:
      name: 高级织布机
      desc: 这间设备齐全的工坊配备了最先进的织布机和缝纫桌，桌上按序陈设着精心挑选出的高级布料与专业工具，是资深裁缝打造精美服饰的理想之地。
    basicLoom:
      name: 初级织布机
      desc: 这间简朴的工坊内有一台结实的织布机和一张陈旧的缝纫桌，桌上摆满了各式布料与工具，是渴望学习的新人裁缝磨练技术的理想之地。
  trinketry:
    basicTrinketryBench:
      name: 初级珠宝工作台
      desc: 一个用于切割宝石和制作简单饰品的工作台。
    advancedTrinketryBench:
      name: 高级珠宝工作台
      desc: 一张朴素的工作台，上面摆满了镜片、砂纸以及其他可用于制作饰品的各类工具。
    ruinedTrinketryBench:
      desc: 位于雪融之地的废墟中的古老珠宝工作台，木质表面上覆盖着大量的苔藓和蘑菇群。
      name: 破败的珠宝工作台（初级）
    erdwissTrinketryFactory:
      name: 埃德怀斯珠宝工厂（高级）
      desc: 这间工厂拥有从风铸城进口的最精良的设备，可以更精细地切割宝石。
maps:
  tiers:
    "basic": 基础
    "advanced": 高级
    "legendary": 传说
    "mythic": 神话
